-- ========================================
-- 1. ОБНОВЛЕНИЕ БРЕНДОВ
-- ========================================
UPDATE public.products
SET firm = CASE firm
    WHEN '361' THEN '361°'
    WHEN '404mob gang' THEN '404MOB GANG'
    WHEN '7 sevfun' THEN '7 SEVFUN'
    WHEN '88rising' THEN '88rising'
    WHEN 'a chock' THEN 'A Chock'
    WHEN 'a square root' THEN 'A SQUARE ROOT'
    WHEN 'a.b.x' THEN 'A.B.X'
    WHEN 'a02' THEN 'A02'
    WHEN 'aajf' THEN 'AAJF'
    WHEN 'acuc' THEN 'ACUC'
    WHEN 'adidas' THEN 'Adidas'
    WHEN 'agsdon' THEN 'agsdon'
    WHEN 'aokang' THEN 'AOKANG'
    WHEN 'arcteryx' THEN 'Arcteryx'
    WHEN 'asics' THEN 'ASICS'
    WHEN 'atry' THEN 'Atry'
    WHEN 'auldey' THEN 'AULDEY'
    WHEN 'baggl' THEN 'BAGGL'
    WHEN 'balenciaga' THEN 'Balenciaga'
    WHEN 'baleno' THEN 'BALENO'

    WHEN 'bandai' THEN 'bandai'
    WHEN 'banpresto' THEN 'banpresto'
    WHEN 'barbie' THEN 'Barbie'
    WHEN 'barbour' THEN 'barbour'
    WHEN 'beaster' THEN 'BEASTER'
    WHEN 'beerus' THEN 'Beerus'
    WHEN 'beneunder' THEN 'beneunder'
    WHEN 'benmyshower' THEN 'BENMYSHOWER'
    WHEN 'bingfei' THEN 'bingfei'
    WHEN 'birkenstock' THEN 'Birkenstock'
    WHEN 'bjhg' THEN 'BJHG'
    WHEN 'burberry' THEN 'Burberry'
    WHEN 'camel' THEN 'CAMEL'
    WHEN 'caramella' THEN 'Caramella'
    WHEN 'cardanro' THEN 'CARDANRO'
    WHEN 'carhartt' THEN 'Carhartt WIP'
    WHEN 'cartelo' THEN 'cartelo'
    WHEN 'casio' THEN 'CASIO'
    WHEN 'cat' THEN 'CAT'
    WHEN 'champion' THEN 'Champion'
    WHEN 'chanel' THEN 'CHANEL'
    WHEN 'clarks' THEN 'Clarks'
    WHEN 'clot' THEN 'CLOT'
    WHEN 'cmfy' THEN 'CMFY'
    WHEN 'coach' THEN 'COACH'
    WHEN 'columbia' THEN 'Columbia'
    WHEN 'comowa' THEN 'COMOWA'
    WHEN 'converse' THEN 'Converse'
    WHEN 'cooraree' THEN 'Cooraree'
    WHEN 'crocs' THEN 'Crocs'
    WHEN 'dand' THEN 'DAND'
    WHEN 'danqin' THEN 'Danqin'
    WHEN 'deerway' THEN 'DEERWAY'
    WHEN 'devanro' THEN 'Devanro'
    WHEN 'dickies' THEN 'Dickies'
    WHEN 'diesel' THEN 'DIESEL'
    WHEN 'dior' THEN 'DIOR'
    WHEN 'disney' THEN 'Disney'
    WHEN 'doraemon' THEN 'Doraemon'
    WHEN 'dounkol' THEN 'Dounkol'
    WHEN 'dzp' THEN 'DZP'
    WHEN 'ecco' THEN 'Ecco'
    WHEN 'elle' THEN 'ELLE'
    WHEN 'enfantin' THEN 'ENFANTIN'
    WHEN 'eptison' THEN 'EPTISON'
    WHEN 'er' THEN 'ER'
    WHEN 'erke' THEN 'erke'
    WHEN 'eusu' THEN 'EUSU'
    WHEN 'f426' THEN 'F426'
    WHEN 'fairwhale' THEN 'FAIRWHALE'
    WHEN 'fastfish' THEN 'FASTFISH'
    WHEN 'feiyue' THEN 'feiyue'
    WHEN 'ferragamo' THEN 'Ferragamo'
    WHEN 'fila' THEN 'FILA'
    WHEN 'firemonkey' THEN 'FireMonkey'
    WHEN 'fornines' THEN 'FORNINES'
    WHEN 'fpa' THEN 'fpa'
    WHEN 'gbxm' THEN 'GBXM'
    WHEN 'gelanlu' THEN 'GELANLU'
    WHEN 'genanx' THEN 'GENANX'
    WHEN 'givenchy' THEN 'Givenchy'
    WHEN 'golf' THEN 'GOLF'
    WHEN 'golfcross' THEN 'GOLFCROSS'
    WHEN 'gucci' THEN 'GUCCI'
    WHEN 'gudud' THEN 'GUDUD'
    WHEN 'guuka' THEN 'Guuka'
    WHEN 'gwaf' THEN 'GWAF'
    WHEN 'gxg' THEN 'GXG'
    WHEN 'handaiwei' THEN 'handaiwei'
    WHEN 'hanqiaoriji' THEN 'HANQIAORIJI'
    WHEN 'hermes' THEN 'HERMES'
    WHEN 'hla' THEN 'HLA'
    WHEN 'huanai' THEN 'huanai'
    WHEN 'huanqiu' THEN 'HUANQIU'
    WHEN 'iots' THEN 'IOTS'
    WHEN 'jacquemus' THEN 'Jacquemus'
    WHEN 'jaguar' THEN 'JAGUAR'
    WHEN 'jasonwood' THEN 'JASONWOOD'
    WHEN 'jeanswest' THEN 'jeanswest'
    WHEN 'jeep' THEN 'JEEP SPIRIT'
    WHEN 'jellycat' THEN 'jellycat'
    WHEN 'jifeishi' THEN 'jifeishi'
    WHEN 'jkem' THEN 'JKEM'
    WHEN 'jordan' THEN 'Jordan'
    WHEN 'josiny' THEN 'JOSINY'
    WHEN 'kaltendin' THEN 'Kaltendin'
    WHEN 'kangol' THEN 'kangol'
    WHEN 'kappa' THEN 'kappa'
    WHEN 'kelme' THEN 'KELME'
    WHEN 'keen' THEN 'Keen'
    WHEN 'kenmont' THEN 'KENMONT'
    WHEN 'khadgar' THEN 'Khadgar'
    WHEN 'killwinner' THEN 'KILLWINNER'
    WHEN 'kith' THEN 'KITH'
    WHEN 'lacoste' THEN 'lacoste'
    WHEN 'lanza' THEN 'Lanza'
    WHEN 'lee' THEN 'lee'
    WHEN 'lilbetter' THEN 'Lilbetter'
    WHEN 'lingjie' THEN 'LINGJIE'
    WHEN 'lining' THEN 'LINING'
    WHEN 'lululemon' THEN 'Lululemon'
    WHEN 'longchamp' THEN 'longchamp'
    WHEN 'loox' THEN 'LOOX!'
    WHEN 'maserati' THEN 'Maserati'
    WHEN 'melsmao' THEN 'MELSMAO'
    WHEN 'merrell' THEN 'MERRELL'
    WHEN 'mexican' THEN 'MEXICAN'
    WHEN 'miiow' THEN 'MIIOW'
    WHEN 'minifocus' THEN 'minifocus'
    WHEN 'miniso' THEN 'MINISO'
    WHEN 'mizuno' THEN 'Mizuno'
    WHEN 'mlb' THEN 'MLB'
    WHEN 'mover' THEN 'MOVER'
    WHEN 'mpux' THEN 'MPUX'
    WHEN 'mulinsen' THEN 'Mulinsen'
    WHEN 'mustkoo' THEN 'MUSTKOO'
    WHEN 'muykuy' THEN 'MUYKUY'
    WHEN 'nike' THEN 'Nike'
    WHEN 'nothomme' THEN 'NOTHOMME'
    WHEN 'occupy' THEN 'OCCUPY'
    WHEN 'on' THEN 'ON'
    WHEN 'opox' THEN 'OPOX'
    WHEN 'palace' THEN 'palace'
    WHEN 'peak' THEN 'PEAK'
    WHEN 'potdemiel' THEN 'potdemiel'
    WHEN 'prada' THEN 'PRADA'
    WHEN 'pressure' THEN 'PRESSURE'
    WHEN 'puma' THEN 'PUMA'
    WHEN 'qiaodan' THEN 'qiaodan'
    WHEN 'qnxeey' THEN 'Qnxeey'
    WHEN 'rass' THEN 'RASS'
    WHEN 'rastaclat' THEN 'Rastaclat'
    WHEN 'recoleta' THEN 'RECOLETA'
    WHEN 'reebok' THEN 'Reebok'
    WHEN 'renben' THEN 'renben'
    WHEN 'represent' THEN 'REPRESENT'
    WHEN 'rigorer' THEN 'RIGORER'
    WHEN 'ringlove' THEN 'Ringlove'
    WHEN 'robinhood' THEN 'ROBINHOOD'
    WHEN 'salomon' THEN 'SALOMON'
    WHEN 'sandknit' THEN 'SandKnit'
    WHEN 'skechers' THEN 'Skechers'
    WHEN 'skmei' THEN 'SKMEI'
    WHEN 'sleepywalk' THEN 'sleepywalk'
    WHEN 'smfk' THEN 'SMFK'
    WHEN 'sockkey' THEN 'SOCKKEY'
    WHEN 'soie' THEN 'SOIE'
    WHEN 'sprayground' THEN 'SPRAYGROUND'
    WHEN 'spyder' THEN 'SPYDER'
    WHEN 'stussy' THEN 'Stussy'
    WHEN 'suamoment' THEN 'Suamoment'
    WHEN 'sunsetmonent' THEN 'SUNSETMONENT'
    WHEN 'supreme' THEN 'Supreme'
    WHEN 'swarovski' THEN 'Swarovski'
    WHEN 'teenmix' THEN 'teenmix'
    WHEN 'telent' THEN 'TELENT'
    WHEN 'thrasher' THEN 'Thrasher'
    WHEN 'timberland' THEN 'Timberland'
    WHEN 'tkb' THEN 'Tkb'
    WHEN 'tonlion' THEN 'Tonlion'
    WHEN 'tucano' THEN 'TUCANO'
    WHEN 'ugg' THEN 'UGG'
    WHEN 'unthemed' THEN 'UNthemed'
    WHEN 'us8acc' THEN 'US8ACC'
    WHEN 'ux' THEN 'ux'
    WHEN 'uzis' THEN 'UZIS'
    WHEN 'vans' THEN 'Vans'
    WHEN 'veidoorn' THEN 'VEIDOORN'
    WHEN 'warrior' THEN 'WARRIOR'
    WHEN 'whoosis' THEN 'WHOOSIS'
    WHEN 'wodonble' THEN 'WODONBLE'
    WHEN 'wuji' THEN 'WUJI'
    WHEN 'xinyinsu' THEN 'XINYINSU'
    WHEN 'xtep' THEN 'XTEP'
    WHEN 'yaya' THEN 'yaya'
    WHEN 'yeezy' THEN 'YEEZY'
    WHEN 'yichen' THEN 'YICHEN'
    WHEN 'yoasobi' THEN 'YOASOBI'
    WHEN 'zanc' THEN 'ZANC'
    WHEN 'zippo' THEN 'ZIPPO'
    ELSE firm
END
WHERE firm IN (
    '361',  '404mob gang', '7 sevfun', '88rising','adidas', 'a chock', 'a square root', 
    'a.b.x', 'a02', 'aajf', 'acuc', 'agsdon', 'aokang', 'arcteryx', 'asics', 'atry', 
    'auldey','baggl', 'balenciaga', 'baleno', 'bandai', 'banpresto', 'barbie', 'barbour', 
    'beaster', 'beerus', 'beneunder', 'benmyshower', 'bingfei', 'birkenstock', 'bjhg', 
    'burberry', 'camel', 'caramella', 'cardanro', 'carhartt', 'cartelo', 'casio', 'cat', 
    'champion', 'chanel', 'clarks', 'clot', 'cmfy', 'coach', 'columbia', 'comowa', 
    'converse', 'cooraree', 'crocs', 'dand', 'danqin', 'deerway', 'devanro', 'dickies', 
    'diesel', 'dior', 'disney', 'doraemon', 'dounkol', 'dzp', 'ecco', 'elle', 'enfantin', 
    'eptison', 'er', 'erke', 'eusu', 'f426', 'fairwhale', 'fastfish', 'feiyue', 
    'ferragamo', 'fila', 'firemonkey', 'fornines', 'fpa', 'gbxm', 'gelanlu', 'genanx', 
    'givenchy', 'golf', 'golfcross', 'gucci', 'gudud', 'guuka', 'gwaf', 'gxg', 
    'handaiwei', 'hanqiaoriji', 'hermes', 'hla', 'huanai', 'huanqiu', 'jacquemus', 
    'jaguar', 'jasonwood', 'jeanswest', 'jeep', 'jellycat', 'jifeishi', 'jkem', 'jordan', 
    'josiny', 'kaltendin', 'kangol', 'kappa', 'kelme', 'keen', 'kenmont', 'khadgar', 
    'killwinner', 'kith', 'lacoste', 'lanza', 'lee', 'lilbetter', 'lingjie', 'lining', 
    'lululemon', 'longchamp', 'loox', 'maserati', 'melsmao', 'merrell', 'mexican', 
    'miiow', 'minifocus', 'miniso', 'mizuno', 'mlb', 'mover', 'mpux', 'mulinsen', 
    'mustkoo', 'muykuy', 'nike', 'nothomme', 'occupy', 'on', 'opox', 'palace', 'peak', 
    'potdemiel', 'prada', 'pressure', 'puma', 'qiaodan', 'qnxeey', 'rass', 'rastaclat', 
    'recoleta', 'reebok', 'renben', 'represent', 'rigorer', 'ringlove', 'robinhood', 
    'salomon', 'sandknit', 'skechers', 'skmei', 'sleepywalk', 'smfk', 'sockkey', 'soie', 
    'sprayground', 'spyder', 'stussy', 'suamoment', 'sunsetmonent', 'supreme', 
    'swarovski', 'teenmix', 'telent', 'thrasher', 'timberland', 'tkb', 'tonlion', 
    'tucano', 'ugg', 'unthemed', 'us8acc', 'ux', 'uzis', 'vans', 'veidoorn', 'warrior', 
    'whoosis', 'wodonble', 'wuji', 'xinyinsu', 'xtep', 'yaya', 'yeezy', 'yichen', 
    'yoasobi', 'zanc', 'zippo'
);
