// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: admin.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateBrandActive = `-- name: BulkUpdateBrandActive :exec
UPDATE brands
SET is_active = $1,
    updated_at = NOW()
WHERE id = ANY($2::int [])
`

type BulkUpdateBrandActiveParams struct {
	Active bool    `json:"active"`
	Ids    []int32 `json:"ids"`
}

func (q *Queries) BulkUpdateBrandActive(ctx context.Context, arg BulkUpdateBrandActiveParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateBrandActive, arg.Active, arg.Ids)
	return err
}

const bulkUpdateBrandSortOrder = `-- name: BulkUpdateBrandSortOrder :exec
UPDATE brands
SET sort_order = $1,
    updated_at = NOW()
WHERE id = ANY($2::int [])
`

type BulkUpdateBrandSortOrderParams struct {
	SortOrder int32   `json:"sort_order"`
	Ids       []int32 `json:"ids"`
}

func (q *Queries) BulkUpdateBrandSortOrder(ctx context.Context, arg BulkUpdateBrandSortOrderParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateBrandSortOrder, arg.SortOrder, arg.Ids)
	return err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, password_hash, name, role, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id,
    email,
    name,
    role,
    is_active,
    created_at
`

type CreateAdminParams struct {
	Email        string        `json:"email"`
	PasswordHash []byte        `json:"password_hash"`
	Name         string        `json:"name"`
	Role         AdminRoleEnum `json:"role"`
	IsActive     pgtype.Bool   `json:"is_active"`
}

type CreateAdminRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      AdminRoleEnum      `json:"role"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (CreateAdminRow, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.IsActive,
	)
	var i CreateAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createAdminInvite = `-- name: CreateAdminInvite :one
INSERT INTO admin_invites (email, role, token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, role, token, invited_by, expires_at, used_at, used_by, created_at, updated_at
`

type CreateAdminInviteParams struct {
	Email     string             `json:"email"`
	Role      AdminRoleEnum      `json:"role"`
	Token     string             `json:"token"`
	InvitedBy pgtype.Int4        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminInvite(ctx context.Context, arg CreateAdminInviteParams) (AdminInvite, error) {
	row := q.db.QueryRow(ctx, createAdminInvite,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i AdminInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminLog = `-- name: CreateAdminLog :exec
INSERT INTO admin_logs (
        admin_id,
        action,
        entity_type,
        entity_id,
        details,
        ip_address
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAdminLogParams struct {
	AdminID    int32       `json:"admin_id"`
	Action     string      `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
	EntityID   pgtype.Int4 `json:"entity_id"`
	Details    pgtype.Text `json:"details"`
	IpAddress  *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateAdminLog(ctx context.Context, arg CreateAdminLogParams) error {
	_, err := q.db.Exec(ctx, createAdminLog,
		arg.AdminID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	return err
}

const createAdminPasswordResetToken = `-- name: CreateAdminPasswordResetToken :exec
INSERT INTO admin_password_resets (email, token, expires_at)
VALUES ($1, $2, NOW() + INTERVAL '1 hour') ON CONFLICT (email) DO
UPDATE
SET token = EXCLUDED.token,
    expires_at = NOW() + INTERVAL '1 hour',
    used_at = NULL
`

type CreateAdminPasswordResetTokenParams struct {
	Email string `json:"email"`
	Token string `json:"token"`
}

func (q *Queries) CreateAdminPasswordResetToken(ctx context.Context, arg CreateAdminPasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createAdminPasswordResetToken, arg.Email, arg.Token)
	return err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admins
WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const deleteAdminByEmail = `-- name: DeleteAdminByEmail :exec
DELETE FROM admins
WHERE email = $1
`

func (q *Queries) DeleteAdminByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteAdminByEmail, email)
	return err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brands WHERE id = $1
`

func (q *Queries) DeleteBrand(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBrand, id)
	return err
}

const deleteOldPasswordResetTokenByEmail = `-- name: DeleteOldPasswordResetTokenByEmail :exec
DELETE FROM admin_password_resets
WHERE email = $1
    AND (
        expires_at < NOW()
        OR used_at IS NOT NULL
    )
`

func (q *Queries) DeleteOldPasswordResetTokenByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOldPasswordResetTokenByEmail, email)
	return err
}

const deleteOldPasswordResetTokens = `-- name: DeleteOldPasswordResetTokens :exec
DELETE FROM admin_password_resets
WHERE expires_at < NOW()
    OR used_at IS NOT NULL
`

func (q *Queries) DeleteOldPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldPasswordResetTokens)
	return err
}

const getAdminBanners = `-- name: GetAdminBanners :many
SELECT id,
    title,
    image_url,
    link_url,
    is_active,
    created_at
FROM banners
`

type GetAdminBannersRow struct {
	ID        int32              `json:"id"`
	Title     pgtype.Text        `json:"title"`
	ImageUrl  string             `json:"image_url"`
	LinkUrl   string             `json:"link_url"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminBanners(ctx context.Context) ([]GetAdminBannersRow, error) {
	rows, err := q.db.Query(ctx, getAdminBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminBannersRow
	for rows.Next() {
		var i GetAdminBannersRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id,
    email,
    password_hash,
    name,
    role,
    is_active,
    last_login_at,
    last_login_ip,
    created_at
FROM admins
WHERE email = $1
LIMIT 1
`

type GetAdminByEmailRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         AdminRoleEnum      `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp  *netip.Addr        `json:"last_login_ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (GetAdminByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i GetAdminByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id,
    email,
    password_hash,
    name,
    role,
    is_active,
    last_login_at,
    last_login_ip,
    created_at
FROM admins
WHERE id = $1
LIMIT 1
`

type GetAdminByIDRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         AdminRoleEnum      `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp  *netip.Addr        `json:"last_login_ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminByID(ctx context.Context, id int32) (GetAdminByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i GetAdminByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByResetToken = `-- name: GetAdminByResetToken :one
SELECT a.id,
    a.email,
    a.name,
    a.role,
    a.is_active
FROM admin_password_resets r
    JOIN admins a ON a.email = r.email
WHERE r.token = $1
    AND r.expires_at > NOW()
    AND r.used_at IS NULL
    AND a.is_active = true
`

type GetAdminByResetTokenRow struct {
	ID       int32         `json:"id"`
	Email    string        `json:"email"`
	Name     string        `json:"name"`
	Role     AdminRoleEnum `json:"role"`
	IsActive pgtype.Bool   `json:"is_active"`
}

func (q *Queries) GetAdminByResetToken(ctx context.Context, token string) (GetAdminByResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getAdminByResetToken, token)
	var i GetAdminByResetTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
WITH product_stats AS (
    SELECT COALESCE(COUNT(DISTINCT p.id), 0)::int as total_products,
        COALESCE(COUNT(DISTINCT p.brand_id), 0)::int as total_firms,
        COALESCE(COUNT(DISTINCT p.category), 0)::int as total_categories
    FROM products p
),
order_stats AS (
    SELECT COALESCE(
            COUNT(
                CASE
                    WHEN o.status = 'pending' THEN 1
                END
            ),
            0
        )::int as pending_orders,
        COALESCE(
            COUNT(
                CASE
                    WHEN o.status = 'approved' THEN 1
                END
            ),
            0
        )::int as approved_orders,
        COALESCE(
            COUNT(
                CASE
                    WHEN o.status = 'rejected' THEN 1
                END
            ),
            0
        )::int as rejected_orders,
        COALESCE(COUNT(*), 0)::int as total_orders,
        COALESCE(SUM(oi.price * oi.quantity), 0)::int as total_revenue
    FROM orders o
        LEFT JOIN orderitems oi ON o.id = oi.orderid
        AND o.status = 'approved'
),
user_stats AS (
    SELECT COALESCE(COUNT(DISTINCT c.id), 0)::int as registered_users,
        (
            SELECT COALESCE(COUNT(*), 0)::int
            FROM uniquecustomers
        ) as unique_visitors,
        COALESCE(COUNT(DISTINCT u.id), 0)::int as unregistered_customers,
        COALESCE(
            COUNT(
                DISTINCT CASE
                    WHEN c.id IS NOT NULL
                    AND c.created_at >= NOW() - INTERVAL '30 days' THEN c.id
                END
            ),
            0
        )::int as new_users_30d
    FROM customers c
        FULL JOIN unregistercustomer u ON false
),
stock_stats AS (
    SELECT COALESCE(COUNT(DISTINCT sh.productid), 0)::int as products_in_stock,
        COALESCE(SUM(sh.quantity), 0)::int as total_items_in_stock,
        COALESCE(
            COUNT(
                CASE
                    WHEN sh.quantity = 0 THEN 1
                END
            ),
            0
        )::int as out_of_stock_items
    FROM store_house sh
),
discount_stats AS (
    SELECT COALESCE(COUNT(DISTINCT d.productid), 0)::int as products_on_discount,
        COALESCE(COUNT(*), 0)::int as active_discounts
    FROM discount d
),
recent_activity AS (
    SELECT COALESCE(COUNT(*), 0)::int as orders_last_7_days
    FROM orders o
    WHERE o.orderdate >= CURRENT_DATE - INTERVAL '7 days'
)
SELECT ps.total_products,
    ps.total_firms,
    ps.total_categories,
    os.pending_orders,
    os.approved_orders,
    os.rejected_orders,
    os.total_orders,
    os.total_revenue,
    us.registered_users,
    us.unique_visitors,
    us.unregistered_customers,
    us.new_users_30d,
    ss.products_in_stock,
    ss.total_items_in_stock,
    ss.out_of_stock_items,
    ds.products_on_discount,
    ds.active_discounts,
    ra.orders_last_7_days
FROM product_stats ps,
    order_stats os,
    user_stats us,
    stock_stats ss,
    discount_stats ds,
    recent_activity ra
`

type GetAdminDashboardStatsRow struct {
	TotalProducts         int32 `json:"total_products"`
	TotalFirms            int32 `json:"total_firms"`
	TotalCategories       int32 `json:"total_categories"`
	PendingOrders         int32 `json:"pending_orders"`
	ApprovedOrders        int32 `json:"approved_orders"`
	RejectedOrders        int32 `json:"rejected_orders"`
	TotalOrders           int32 `json:"total_orders"`
	TotalRevenue          int32 `json:"total_revenue"`
	RegisteredUsers       int32 `json:"registered_users"`
	UniqueVisitors        int32 `json:"unique_visitors"`
	UnregisteredCustomers int32 `json:"unregistered_customers"`
	NewUsers30d           int32 `json:"new_users_30d"`
	ProductsInStock       int32 `json:"products_in_stock"`
	TotalItemsInStock     int32 `json:"total_items_in_stock"`
	OutOfStockItems       int32 `json:"out_of_stock_items"`
	ProductsOnDiscount    int32 `json:"products_on_discount"`
	ActiveDiscounts       int32 `json:"active_discounts"`
	OrdersLast7Days       int32 `json:"orders_last_7_days"`
}

func (q *Queries) GetAdminDashboardStats(ctx context.Context) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats)
	var i GetAdminDashboardStatsRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalFirms,
		&i.TotalCategories,
		&i.PendingOrders,
		&i.ApprovedOrders,
		&i.RejectedOrders,
		&i.TotalOrders,
		&i.TotalRevenue,
		&i.RegisteredUsers,
		&i.UniqueVisitors,
		&i.UnregisteredCustomers,
		&i.NewUsers30d,
		&i.ProductsInStock,
		&i.TotalItemsInStock,
		&i.OutOfStockItems,
		&i.ProductsOnDiscount,
		&i.ActiveDiscounts,
		&i.OrdersLast7Days,
	)
	return i, err
}

const getAdminInviteByToken = `-- name: GetAdminInviteByToken :one
SELECT id, email, role, token, invited_by, expires_at, used_at, used_by, created_at, updated_at FROM admin_invites
WHERE token = $1 
  AND used_at IS NULL 
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetAdminInviteByToken(ctx context.Context, token string) (AdminInvite, error) {
	row := q.db.QueryRow(ctx, getAdminInviteByToken, token)
	var i AdminInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminLogs = `-- name: GetAdminLogs :many
SELECT al.id,
    al.admin_id,
    a.email as admin_email,
    a.name as admin_name,
    al.action,
    al.entity_type,
    al.entity_id,
    al.details,
    al.ip_address,
    al.created_at
FROM admin_logs al
    LEFT JOIN admins a ON al.admin_id = a.id
WHERE (
        $3::int IS NULL
        OR al.admin_id = $3
    )
    AND (
        $4::text IS NULL
        OR al.action = $4
    )
    AND (
        $5::timestamptz IS NULL
        OR al.created_at >= $5
    )
    AND (
        $6::timestamptz IS NULL
        OR al.created_at <= $6
    )
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAdminLogsParams struct {
	Limit    int32              `json:"limit"`
	Offset   int32              `json:"offset"`
	AdminID  pgtype.Int4        `json:"admin_id"`
	Action   pgtype.Text        `json:"action"`
	DateFrom pgtype.Timestamptz `json:"date_from"`
	DateTo   pgtype.Timestamptz `json:"date_to"`
}

type GetAdminLogsRow struct {
	ID         int32              `json:"id"`
	AdminID    int32              `json:"admin_id"`
	AdminEmail pgtype.Text        `json:"admin_email"`
	AdminName  pgtype.Text        `json:"admin_name"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Int4        `json:"entity_id"`
	Details    pgtype.Text        `json:"details"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAdminLogs(ctx context.Context, arg GetAdminLogsParams) ([]GetAdminLogsRow, error) {
	rows, err := q.db.Query(ctx, getAdminLogs,
		arg.Limit,
		arg.Offset,
		arg.AdminID,
		arg.Action,
		arg.DateFrom,
		arg.DateTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminLogsRow
	for rows.Next() {
		var i GetAdminLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AdminEmail,
			&i.AdminName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminLogsCount = `-- name: GetAdminLogsCount :one
SELECT COUNT(*)
FROM admin_logs al
WHERE (
        $1::int IS NULL
        OR al.admin_id = $1
    )
    AND (
        $2::text IS NULL
        OR al.action = $2
    )
    AND (
        $3::text IS NULL
        OR al.entity_type = $3
    )
`

type GetAdminLogsCountParams struct {
	AdminID    pgtype.Int4 `json:"admin_id"`
	Action     pgtype.Text `json:"action"`
	EntityType pgtype.Text `json:"entity_type"`
}

// ========== ЛОГИ АДМИНИСТРАТОРОВ ==========
func (q *Queries) GetAdminLogsCount(ctx context.Context, arg GetAdminLogsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAdminLogsCount, arg.AdminID, arg.Action, arg.EntityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminProductsInfoById = `-- name: GetAdminProductsInfoById :one
SELECT p.sizes,
    p.id AS id,
    p.image_path,
    p.name,
    d.value AS value,
    COALESCE(
        jsonb_object_agg(st.size, st.quantity) FILTER (
            WHERE st.size IS NOT NULL
        ),
        '{}'::jsonb
    ) as store_info,
    p.article,
    p.description,
    bl.name as line,
    p.type,
    p.category,
    p.date,
    b.name as firm,
    p.status,
    p.image_count
FROM products p
    LEFT JOIN discount d ON p.id = d.productid
    LEFT JOIN store_house st ON p.id = st.productid
    JOIN brands b ON p.brand_id = b.id
    LEFT JOIN brand_lines bl ON p.line_id = bl.id
WHERE p.id = $1
GROUP BY p.id,
    d.value,
    b.name,
    bl.name
`

type GetAdminProductsInfoByIdRow struct {
	Sizes       []byte      `json:"sizes"`
	ID          int32       `json:"id"`
	ImagePath   string      `json:"image_path"`
	Name        string      `json:"name"`
	Value       []byte      `json:"value"`
	StoreInfo   interface{} `json:"store_info"`
	Article     string      `json:"article"`
	Description pgtype.Text `json:"description"`
	Line        pgtype.Text `json:"line"`
	Type        int32       `json:"type"`
	Category    int32       `json:"category"`
	Date        pgtype.Text `json:"date"`
	Firm        string      `json:"firm"`
	Status      string      `json:"status"`
	ImageCount  int32       `json:"image_count"`
}

func (q *Queries) GetAdminProductsInfoById(ctx context.Context, id int32) (GetAdminProductsInfoByIdRow, error) {
	row := q.db.QueryRow(ctx, getAdminProductsInfoById, id)
	var i GetAdminProductsInfoByIdRow
	err := row.Scan(
		&i.Sizes,
		&i.ID,
		&i.ImagePath,
		&i.Name,
		&i.Value,
		&i.StoreInfo,
		&i.Article,
		&i.Description,
		&i.Line,
		&i.Type,
		&i.Category,
		&i.Date,
		&i.Firm,
		&i.Status,
		&i.ImageCount,
	)
	return i, err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT COUNT(*) as total_admins,
    COUNT(
        CASE
            WHEN role = 'superadmin' THEN 1
        END
    ) as superadmins,
    COUNT(
        CASE
            WHEN role = 'admin' THEN 1
        END
    ) as regular_admins,
    COUNT(
        CASE
            WHEN is_active = true THEN 1
        END
    ) as active_admins
FROM admins
`

type GetAdminStatsRow struct {
	TotalAdmins   int64 `json:"total_admins"`
	Superadmins   int64 `json:"superadmins"`
	RegularAdmins int64 `json:"regular_admins"`
	ActiveAdmins  int64 `json:"active_admins"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.TotalAdmins,
		&i.Superadmins,
		&i.RegularAdmins,
		&i.ActiveAdmins,
	)
	return i, err
}

const getAdminsList = `-- name: GetAdminsList :many
SELECT id,
    email,
    name,
    role,
    is_active,
    last_login_at,
    last_login_ip,
    created_at
FROM admins
WHERE (
        $1::admin_role_enum IS NULL
        OR role = $1
    )
    AND (
        $2::boolean IS NULL
        OR is_active = $2
    )
    AND (
        $3::text IS NULL
        OR email ILIKE '%' || $3 || '%'
        OR name ILIKE '%' || $3 || '%'
    )
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type GetAdminsListParams struct {
	Role      NullAdminRoleEnum `json:"role"`
	IsActive  pgtype.Bool       `json:"is_active"`
	Search    pgtype.Text       `json:"search"`
	OffsetVal int32             `json:"offset_val"`
	LimitVal  int32             `json:"limit_val"`
}

type GetAdminsListRow struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        AdminRoleEnum      `json:"role"`
	IsActive    pgtype.Bool        `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp *netip.Addr        `json:"last_login_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// ========== АДМИНИСТРАТОРЫ ==========
func (q *Queries) GetAdminsList(ctx context.Context, arg GetAdminsListParams) ([]GetAdminsListRow, error) {
	rows, err := q.db.Query(ctx, getAdminsList,
		arg.Role,
		arg.IsActive,
		arg.Search,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminsListRow
	for rows.Next() {
		var i GetAdminsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFiltersForAdmin = `-- name: GetAllFiltersForAdmin :one
WITH all_products AS (
    SELECT p.id,
        p.brand_id,
        b.name as firm,
        p.minprice,
        p.maxprice,
        p.sizes,
        p.bodytype,
        p.type as product_type_id,
        p.category as category_id,
        p.status
    FROM products p
        JOIN brands b ON p.brand_id = b.id
    WHERE p.status != 'deleted'
),
size_data AS (
    SELECT size_key,
        COUNT(*) as count
    FROM all_products
        CROSS JOIN LATERAL jsonb_object_keys(sizes) as size_key
    WHERE (sizes->size_key->>'price')::numeric > 0
    GROUP BY size_key
),
firm_counts AS (
    SELECT firm,
        COUNT(*) AS firm_count
    FROM all_products
    WHERE firm IS NOT NULL
    GROUP BY firm
),
bodytype_counts AS (
    SELECT bodytype,
        COUNT(*) as count
    FROM all_products
    GROUP BY bodytype
),
price_range AS (
    SELECT COALESCE(MIN(minprice), 0) AS min_price,
        COALESCE(MAX(maxprice), 0) AS max_price
    FROM all_products
),
type_data AS (
    SELECT product_type_id,
        COUNT(*) as type_count,
        (
            SELECT type_name
            FROM product_types
            WHERE id = product_type_id
        ) as type_name
    FROM all_products
    GROUP BY product_type_id
),
category_data AS (
    SELECT category_id,
        COUNT(*) as category_count,
        (
            SELECT name
            FROM product_categories
            WHERE id = category_id
        ) as category_name
    FROM all_products
    GROUP BY category_id
),
status_counts AS (
    SELECT COUNT(*) as total_products,
        COUNT(
            CASE
                WHEN status = 'active' THEN 1
            END
        ) as active_products,
        COUNT(
            CASE
                WHEN status = 'archived' THEN 1
            END
        ) as archived_products,
        COUNT(
            CASE
                WHEN status = 'draft' THEN 1
            END
        ) as draft_products
    FROM all_products
)
SELECT -- Все размеры
    COALESCE(
        (
            SELECT jsonb_object_agg(size_key, count)
            FROM size_data
        ),
        '{}'::jsonb
    ) as sizes,
    -- Статистика по типам тела
    COALESCE(
        (
            SELECT jsonb_object_agg(bodytype::text, count)
            FROM bodytype_counts
        ),
        '{}'::jsonb
    ) as bodytypes,
    -- Ценовой диапазон
    (
        SELECT min_price
        FROM price_range
    ) as min_price,
    (
        SELECT max_price
        FROM price_range
    ) as max_price,
    -- Статистика по брендам
    COALESCE(
        (
            SELECT jsonb_object_agg(firm, firm_count)
            FROM firm_counts
        ),
        '{}'::jsonb
    ) as firms,
    -- Типы товаров
    COALESCE(
        (
            SELECT jsonb_agg(
                    product_type_id
                )
            FROM type_data
        ),
        '[]'::jsonb
    ) AS product_types, -- Категории товаров
    COALESCE(
        (
            SELECT jsonb_agg(
                    jsonb_build_object(
                        'category_id',
                        category_id,
                        'category_name',
                        category_name,
                        'count',
                        category_count
                    )
                )
            FROM category_data
        ),
        '[]'::jsonb
    ) as categories,
    -- Статистика по статусам
    (
        SELECT total_products
        FROM status_counts
    ) as total_products,
    (
        SELECT active_products
        FROM status_counts
    ) as active_products,
    (
        SELECT archived_products
        FROM status_counts
    ) as archived_products,
    (
        SELECT draft_products
        FROM status_counts
    ) as draft_products
`

type GetAllFiltersForAdminRow struct {
	Sizes            interface{} `json:"sizes"`
	Bodytypes        interface{} `json:"bodytypes"`
	MinPrice         interface{} `json:"min_price"`
	MaxPrice         interface{} `json:"max_price"`
	Firms            interface{} `json:"firms"`
	ProductTypes     interface{} `json:"product_types"`
	Categories       interface{} `json:"categories"`
	TotalProducts    int64       `json:"total_products"`
	ActiveProducts   int64       `json:"active_products"`
	ArchivedProducts int64       `json:"archived_products"`
	DraftProducts    int64       `json:"draft_products"`
}

func (q *Queries) GetAllFiltersForAdmin(ctx context.Context) (GetAllFiltersForAdminRow, error) {
	row := q.db.QueryRow(ctx, getAllFiltersForAdmin)
	var i GetAllFiltersForAdminRow
	err := row.Scan(
		&i.Sizes,
		&i.Bodytypes,
		&i.MinPrice,
		&i.MaxPrice,
		&i.Firms,
		&i.ProductTypes,
		&i.Categories,
		&i.TotalProducts,
		&i.ActiveProducts,
		&i.ArchivedProducts,
		&i.DraftProducts,
	)
	return i, err
}

const getAllProductsForAdmin = `-- name: GetAllProductsForAdmin :many
SELECT p.id,
    p.qId,
    p.name,
    b.name as firm,
    bl.name as line,
    p.image_path,
    p.minprice,
    p.maxprice,
    p.type,
    p.category,
    p.article,
    p.date,
    p.bodytype,
    p.image_count,
    p.updated_at,
    p.sizes,
    p.status,
    pc.name as category_name,
    pt.type_name as type_name,
    -- Наличие на складе
    COALESCE(
        (
            SELECT SUM(sh.quantity)
            FROM store_house sh
            WHERE sh.productid = p.id
        ),
        0
    ) as total_quantity,
    -- Активная скидка
    (
        SELECT jsonb_build_object(
                'value',
                d.value,
                'minprice',
                d.minprice,
                'maxdiscprice',
                d.maxdiscprice
            )
        FROM discount d
        WHERE d.productid = p.id
        LIMIT 1
    ) as discount
FROM products p
    LEFT JOIN product_categories pc ON p.category = pc.id
    LEFT JOIN product_types pt ON p.type = pt.id
    JOIN brands b ON p.brand_id = b.id
    LEFT JOIN brand_lines bl ON p.line_id = bl.id
WHERE p.status != 'deleted'
ORDER BY p.id OFFSET $1
LIMIT $2
`

type GetAllProductsForAdminParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

type GetAllProductsForAdminRow struct {
	ID            int32              `json:"id"`
	Qid           string             `json:"qid"`
	Name          string             `json:"name"`
	Firm          string             `json:"firm"`
	Line          pgtype.Text        `json:"line"`
	ImagePath     string             `json:"image_path"`
	Minprice      int32              `json:"minprice"`
	Maxprice      int32              `json:"maxprice"`
	Type          int32              `json:"type"`
	Category      int32              `json:"category"`
	Article       string             `json:"article"`
	Date          pgtype.Text        `json:"date"`
	Bodytype      BodyEnum           `json:"bodytype"`
	ImageCount    int32              `json:"image_count"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Sizes         []byte             `json:"sizes"`
	Status        string             `json:"status"`
	CategoryName  pgtype.Text        `json:"category_name"`
	TypeName      pgtype.Text        `json:"type_name"`
	TotalQuantity interface{}        `json:"total_quantity"`
	Discount      []byte             `json:"discount"`
}

func (q *Queries) GetAllProductsForAdmin(ctx context.Context, arg GetAllProductsForAdminParams) ([]GetAllProductsForAdminRow, error) {
	rows, err := q.db.Query(ctx, getAllProductsForAdmin, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsForAdminRow
	for rows.Next() {
		var i GetAllProductsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Qid,
			&i.Name,
			&i.Firm,
			&i.Line,
			&i.ImagePath,
			&i.Minprice,
			&i.Maxprice,
			&i.Type,
			&i.Category,
			&i.Article,
			&i.Date,
			&i.Bodytype,
			&i.ImageCount,
			&i.UpdatedAt,
			&i.Sizes,
			&i.Status,
			&i.CategoryName,
			&i.TypeName,
			&i.TotalQuantity,
			&i.Discount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerDetails = `-- name: GetCustomerDetails :one
SELECT c.id, c.name, c.secondname, c.mail, c.pass, c.phone, c.town, c.index, c.sendmail, c.street, c.region, c.home, c.flat, c.coordinates, c.created_at,
    json_agg(
        json_build_object(
            'id',
            o.id,
            'order_date',
            o.orderdate,
            'status',
            o.status,
            'total_amount',
            (
                SELECT COALESCE(SUM(oi.quantity * oi.price), 0)
                FROM orderitems oi
                WHERE oi.orderid = o.id
            ),
            'items_count',
            (
                SELECT COUNT(*)
                FROM orderitems oi
                WHERE oi.orderid = o.id
            )
        )
        ORDER BY o.orderdate DESC
    ) as orders_history
FROM customers c
    LEFT JOIN orders o ON c.id = o.customerid
WHERE c.id = $1
GROUP BY c.id
`

type GetCustomerDetailsRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Secondname    pgtype.Text        `json:"secondname"`
	Mail          string             `json:"mail"`
	Pass          []byte             `json:"pass"`
	Phone         pgtype.Text        `json:"phone"`
	Town          pgtype.Text        `json:"town"`
	Index         pgtype.Text        `json:"index"`
	Sendmail      pgtype.Bool        `json:"sendmail"`
	Street        pgtype.Text        `json:"street"`
	Region        pgtype.Text        `json:"region"`
	Home          pgtype.Text        `json:"home"`
	Flat          pgtype.Text        `json:"flat"`
	Coordinates   []int32            `json:"coordinates"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	OrdersHistory []byte             `json:"orders_history"`
}

func (q *Queries) GetCustomerDetails(ctx context.Context, customerID int32) (GetCustomerDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCustomerDetails, customerID)
	var i GetCustomerDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Secondname,
		&i.Mail,
		&i.Pass,
		&i.Phone,
		&i.Town,
		&i.Index,
		&i.Sendmail,
		&i.Street,
		&i.Region,
		&i.Home,
		&i.Flat,
		&i.Coordinates,
		&i.CreatedAt,
		&i.OrdersHistory,
	)
	return i, err
}

const getCustomersCount = `-- name: GetCustomersCount :one
SELECT COUNT(*)
FROM customers
`

func (q *Queries) GetCustomersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getCustomersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCustomersList = `-- name: GetCustomersList :many
SELECT id,
    name,
    secondname,
    mail,
    phone,
    town,
    index,
    street,
    region,
    home,
    flat,
    sendmail,
    created_at,
    (
        SELECT COUNT(*)
        FROM orders o
        WHERE o.customerid = c.id
    ) as orders_count,
    (
        SELECT COALESCE(SUM(oi.quantity * oi.price), 0)
        FROM orders o
            JOIN orderitems oi ON o.id = oi.orderid
        WHERE o.customerid = c.id
    ) as total_spent,
    (
        SELECT MAX(o.orderdate)
        FROM orders o
        WHERE o.customerid = c.id
    ) as last_order_date
FROM customers c
WHERE (
        $1::text IS NULL
        OR c.name ILIKE '%' || $1 || '%'
        OR c.mail ILIKE '%' || $1 || '%'
        OR c.phone ILIKE '%' || $1 || '%'
    )
ORDER BY CASE
        WHEN $2::text = 'name' THEN c.name
    END ASC,
    CASE
        WHEN $2::text = 'date_desc' THEN c.created_at
    END DESC,
    CASE
        WHEN $2::text = 'orders_desc' THEN orders_count
    END DESC,
    c.created_at DESC
LIMIT $4 OFFSET $3
`

type GetCustomersListParams struct {
	Search    pgtype.Text `json:"search"`
	SortBy    string      `json:"sort_by"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type GetCustomersListRow struct {
	ID            int32              `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Secondname    pgtype.Text        `json:"secondname"`
	Mail          string             `json:"mail"`
	Phone         pgtype.Text        `json:"phone"`
	Town          pgtype.Text        `json:"town"`
	Index         pgtype.Text        `json:"index"`
	Street        pgtype.Text        `json:"street"`
	Region        pgtype.Text        `json:"region"`
	Home          pgtype.Text        `json:"home"`
	Flat          pgtype.Text        `json:"flat"`
	Sendmail      pgtype.Bool        `json:"sendmail"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	OrdersCount   int64              `json:"orders_count"`
	TotalSpent    interface{}        `json:"total_spent"`
	LastOrderDate interface{}        `json:"last_order_date"`
}

// ========== УПРАВЛЕНИЕ ПОЛЬЗОВАТЕЛЯМИ ==========
func (q *Queries) GetCustomersList(ctx context.Context, arg GetCustomersListParams) ([]GetCustomersListRow, error) {
	rows, err := q.db.Query(ctx, getCustomersList,
		arg.Search,
		arg.SortBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersListRow
	for rows.Next() {
		var i GetCustomersListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secondname,
			&i.Mail,
			&i.Phone,
			&i.Town,
			&i.Index,
			&i.Street,
			&i.Region,
			&i.Home,
			&i.Flat,
			&i.Sendmail,
			&i.CreatedAt,
			&i.OrdersCount,
			&i.TotalSpent,
			&i.LastOrderDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT (
        SELECT COUNT(*)
        FROM orders
    ) as total_orders,
    (
        SELECT COUNT(*)
        FROM orders
        WHERE status = 'pending'
    ) as pending_orders,
    (
        SELECT COUNT(*)
        FROM orders
        WHERE status = 'approved'
    ) as approved_orders,
    (
        SELECT COUNT(*)
        FROM orders
        WHERE orderdate = CURRENT_DATE
    ) as today_orders,
    (
        SELECT COUNT(*)
        FROM customers
    ) as total_customers,
    (
        SELECT COUNT(*)
        FROM customers
        WHERE created_at::date = CURRENT_DATE
    ) as today_customers,
    (
        SELECT COALESCE(SUM(oi.quantity * oi.price), 0)
        FROM orders o
            JOIN orderitems oi ON o.id = oi.orderid
        WHERE o.orderdate = CURRENT_DATE
    ) as today_revenue,
    (
        SELECT COALESCE(SUM(oi.quantity * oi.price), 0)
        FROM orders o
            JOIN orderitems oi ON o.id = oi.orderid
        WHERE o.orderdate >= DATE_TRUNC('month', CURRENT_DATE)
    ) as month_revenue,
    (
        SELECT COUNT(*)
        FROM products
        WHERE status = 'active'
    ) as active_products,
    (
        SELECT COUNT(*)
        FROM products
        WHERE status = 'archived'
    ) as archived_products
`

type GetDashboardStatsRow struct {
	TotalOrders      int64       `json:"total_orders"`
	PendingOrders    int64       `json:"pending_orders"`
	ApprovedOrders   int64       `json:"approved_orders"`
	TodayOrders      int64       `json:"today_orders"`
	TotalCustomers   int64       `json:"total_customers"`
	TodayCustomers   int64       `json:"today_customers"`
	TodayRevenue     interface{} `json:"today_revenue"`
	MonthRevenue     interface{} `json:"month_revenue"`
	ActiveProducts   int64       `json:"active_products"`
	ArchivedProducts int64       `json:"archived_products"`
}

// ========== СТАТИСТИКА ДЛЯ ДАШБОРДА ==========
func (q *Queries) GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardStats)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.TotalOrders,
		&i.PendingOrders,
		&i.ApprovedOrders,
		&i.TodayOrders,
		&i.TotalCustomers,
		&i.TodayCustomers,
		&i.TodayRevenue,
		&i.MonthRevenue,
		&i.ActiveProducts,
		&i.ArchivedProducts,
	)
	return i, err
}

const getDiscountRuleByID = `-- name: GetDiscountRuleByID :one
SELECT id
FROM discount_rules
WHERE id = $1::int
`

func (q *Queries) GetDiscountRuleByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getDiscountRuleByID, id)
	err := row.Scan(&id)
	return id, err
}

const getOrderDetails = `-- name: GetOrderDetails :one
SELECT o.id,
    o.customerid,
    o.unregistercustomerid,
    o.orderdate,
    o.status,
    o.hash,
    o.deliveryprice,
    o.deliverytype,
    o.created_at,
    COALESCE(c.name, uc.name)::text as customer_name,
    COALESCE(c.secondname, uc.secondname)::text as customer_secondname,
    COALESCE(c.mail, uc.mail)::text as customer_email,
    COALESCE(c.phone, uc.phone)::text as customer_phone,
    oa.town,
    oa.index,
    oa.street,
    oa.house,
    oa.flat,
    oa.region,
    oa.coordinates,
    oa.deliverycomment,
    (
        SELECT json_agg(
                json_build_object(
                    'id',
                    oi.id,
                    'product_id',
                    oi.productid,
                    'quantity',
                    oi.quantity,
                    'price',
                    oi.price,
                    'name',
                    oi.name,
                    'size',
                    oi.size,
                    'image_path',
                    oi.image_path
                )
            )
        FROM orderitems oi
        WHERE oi.orderid = o.id
    ) as items
FROM orders o
    LEFT JOIN customers c ON o.customerid = c.id
    LEFT JOIN unregistercustomer uc ON o.unregistercustomerid = uc.id
    LEFT JOIN orderaddress oa ON o.id = oa.orderid
WHERE o.id = $1
`

type GetOrderDetailsRow struct {
	ID                   int32              `json:"id"`
	Customerid           pgtype.Int4        `json:"customerid"`
	Unregistercustomerid pgtype.Int4        `json:"unregistercustomerid"`
	Orderdate            pgtype.Date        `json:"orderdate"`
	Status               StatusEnum         `json:"status"`
	Hash                 string             `json:"hash"`
	Deliveryprice        int32              `json:"deliveryprice"`
	Deliverytype         DeliveryEnum       `json:"deliverytype"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CustomerName         string             `json:"customer_name"`
	CustomerSecondname   string             `json:"customer_secondname"`
	CustomerEmail        string             `json:"customer_email"`
	CustomerPhone        string             `json:"customer_phone"`
	Town                 pgtype.Text        `json:"town"`
	Index                pgtype.Text        `json:"index"`
	Street               pgtype.Text        `json:"street"`
	House                pgtype.Text        `json:"house"`
	Flat                 pgtype.Text        `json:"flat"`
	Region               pgtype.Text        `json:"region"`
	Coordinates          []string           `json:"coordinates"`
	Deliverycomment      pgtype.Text        `json:"deliverycomment"`
	Items                []byte             `json:"items"`
}

func (q *Queries) GetOrderDetails(ctx context.Context, orderID int32) (GetOrderDetailsRow, error) {
	row := q.db.QueryRow(ctx, getOrderDetails, orderID)
	var i GetOrderDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Customerid,
		&i.Unregistercustomerid,
		&i.Orderdate,
		&i.Status,
		&i.Hash,
		&i.Deliveryprice,
		&i.Deliverytype,
		&i.CreatedAt,
		&i.CustomerName,
		&i.CustomerSecondname,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Town,
		&i.Index,
		&i.Street,
		&i.House,
		&i.Flat,
		&i.Region,
		&i.Coordinates,
		&i.Deliverycomment,
		&i.Items,
	)
	return i, err
}

const getOrdersCount = `-- name: GetOrdersCount :one
SELECT COUNT(*) as total
FROM orders o
WHERE (
        $1::status_enum IS NULL
        OR o.status = $1
    )
    AND (
        $2::delivery_enum IS NULL
        OR o.deliverytype = $2
    )
    AND (
        $3::date IS NULL
        OR o.orderdate >= $3
    )
    AND (
        $4::date IS NULL
        OR o.orderdate <= $4
    )
`

type GetOrdersCountParams struct {
	Status       NullStatusEnum   `json:"status"`
	DeliveryType NullDeliveryEnum `json:"delivery_type"`
	DateFrom     pgtype.Date      `json:"date_from"`
	DateTo       pgtype.Date      `json:"date_to"`
}

func (q *Queries) GetOrdersCount(ctx context.Context, arg GetOrdersCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOrdersCount,
		arg.Status,
		arg.DeliveryType,
		arg.DateFrom,
		arg.DateTo,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getOrdersWithFilters = `-- name: GetOrdersWithFilters :many
SELECT o.id,
    o.customerid,
    o.unregistercustomerid,
    o.orderdate,
    o.status,
    o.hash,
    o.deliveryprice,
    o.deliverytype,
    o.created_at,
    COALESCE(c.name, uc.name)::text as customer_name,
    COALESCE(c.secondname, uc.secondname)::text as customer_secondname,
    COALESCE(c.mail, uc.mail)::text as customer_email,
    COALESCE(c.phone, uc.phone)::text as customer_phone,
    oa.town,
    oa.street,
    oa.house,
    oa.flat,
    COUNT(oi.id) as items_count,
    COALESCE(SUM(oi.quantity * oi.price), 0) as total_amount
FROM orders o
    LEFT JOIN customers c ON o.customerid = c.id
    LEFT JOIN unregistercustomer uc ON o.unregistercustomerid = uc.id
    LEFT JOIN orderaddress oa ON o.id = oa.orderid
    LEFT JOIN orderitems oi ON o.id = oi.orderid
WHERE (
        $1::status_enum IS NULL
        OR o.status = $1
    )
    AND (
        $2::delivery_enum IS NULL
        OR o.deliverytype = $2
    )
    AND (
        $3::date IS NULL
        OR o.orderdate >= $3
    )
    AND (
        $4::date IS NULL
        OR o.orderdate <= $4
    )
    AND (
        $5::int IS NULL
        OR o.customerid = $5
    )
    AND (
        $6::text IS NULL
        OR o.id::text LIKE '%' || $6 || '%'
        OR c.name ILIKE '%' || $6 || '%'
        OR c.mail ILIKE '%' || $6 || '%'
        OR uc.name ILIKE '%' || $6 || '%'
        OR uc.mail ILIKE '%' || $6 || '%'
    )
GROUP BY o.id,
    c.id,
    uc.id,
    oa.id
ORDER BY CASE
        WHEN $7::text = 'date_desc' THEN o.orderdate
    END DESC,
    CASE
        WHEN $7::text = 'date_asc' THEN o.orderdate
    END ASC,
    CASE
        WHEN $7::text = 'amount_desc' THEN total_amount
    END DESC,
    CASE
        WHEN $7::text = 'amount_asc' THEN total_amount
    END ASC,
    o.orderdate DESC
LIMIT $9 OFFSET $8
`

type GetOrdersWithFiltersParams struct {
	Status       NullStatusEnum   `json:"status"`
	DeliveryType NullDeliveryEnum `json:"delivery_type"`
	DateFrom     pgtype.Date      `json:"date_from"`
	DateTo       pgtype.Date      `json:"date_to"`
	CustomerID   pgtype.Int4      `json:"customer_id"`
	Search       pgtype.Text      `json:"search"`
	SortBy       string           `json:"sort_by"`
	OffsetVal    int32            `json:"offset_val"`
	LimitVal     int32            `json:"limit_val"`
}

type GetOrdersWithFiltersRow struct {
	ID                   int32              `json:"id"`
	Customerid           pgtype.Int4        `json:"customerid"`
	Unregistercustomerid pgtype.Int4        `json:"unregistercustomerid"`
	Orderdate            pgtype.Date        `json:"orderdate"`
	Status               StatusEnum         `json:"status"`
	Hash                 string             `json:"hash"`
	Deliveryprice        int32              `json:"deliveryprice"`
	Deliverytype         DeliveryEnum       `json:"deliverytype"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	CustomerName         string             `json:"customer_name"`
	CustomerSecondname   string             `json:"customer_secondname"`
	CustomerEmail        string             `json:"customer_email"`
	CustomerPhone        string             `json:"customer_phone"`
	Town                 pgtype.Text        `json:"town"`
	Street               pgtype.Text        `json:"street"`
	House                pgtype.Text        `json:"house"`
	Flat                 pgtype.Text        `json:"flat"`
	ItemsCount           int64              `json:"items_count"`
	TotalAmount          interface{}        `json:"total_amount"`
}

func (q *Queries) GetOrdersWithFilters(ctx context.Context, arg GetOrdersWithFiltersParams) ([]GetOrdersWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, getOrdersWithFilters,
		arg.Status,
		arg.DeliveryType,
		arg.DateFrom,
		arg.DateTo,
		arg.CustomerID,
		arg.Search,
		arg.SortBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersWithFiltersRow
	for rows.Next() {
		var i GetOrdersWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Customerid,
			&i.Unregistercustomerid,
			&i.Orderdate,
			&i.Status,
			&i.Hash,
			&i.Deliveryprice,
			&i.Deliverytype,
			&i.CreatedAt,
			&i.CustomerName,
			&i.CustomerSecondname,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Town,
			&i.Street,
			&i.House,
			&i.Flat,
			&i.ItemsCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductIDsForAdminByFilters = `-- name: GetProductIDsForAdminByFilters :many
SELECT p.id
FROM products p
    JOIN brands b ON p.brand_id = b.id
    LEFT JOIN discount d ON p.id = d.productid
    LEFT JOIN store_house sh ON p.id = sh.productid
    LEFT JOIN brand_lines bl ON p.line_id = bl.id
WHERE p.status != 'deleted'
    AND (
        $1::text IS NULL
        OR $1::text = ''
        OR p.status = $1::text
    ) -- Размеры
    AND (
        COALESCE(array_length($2::text [], 1), 0) = 0
        OR EXISTS (
            SELECT 1
            FROM jsonb_object_keys(p.sizes) AS size_key
            WHERE size_key = ANY($2::text [])
                AND (p.sizes->size_key->>'price')::numeric > 0
        )
    ) -- Поиск
    AND (
        $3::text IS NULL
        OR $3::text = ''
        OR p.name ILIKE '%' || $3::text || '%'
        OR p.article ILIKE '%' || $3::text || '%'
    ) -- Категории
    AND (
        COALESCE(array_length($4::int [], 1), 0) = 0
        OR p.category = ANY($4::int [])
    ) -- Типы
    AND (
        COALESCE(array_length($5::int [], 1), 0) = 0
        OR p.type = ANY($5::int [])
    ) -- Фирмы (теперь по brand_id)
    AND (
        COALESCE(array_length($6::int [], 1), 0) = 0
        OR p.brand_id = ANY($6::int [])
    ) -- Линии (теперь по line_id)
    AND (
        COALESCE(array_length($7::int [], 1), 0) = 0
        OR p.line_id = ANY($7::int [])
    ) -- Типы тела
    AND (
        COALESCE(array_length($8::text [], 1), 0) = 0
        OR p.bodytype = ANY($8::body_enum [])
    ) -- Цены
    AND (
        $9::int IS NULL
        OR p.maxprice >= $9::int
    )
    AND (
        $10::int IS NULL
        OR p.minprice <= $10::int
    )
    AND (
        $11::timestamptz IS NULL
        OR p.created_at >= $11::timestamptz
    )
    AND (
        $12::timestamptz IS NULL
        OR p.updated_at >= $12::timestamptz
    ) -- Скидка
    AND (
        $13::boolean IS NULL
        OR $13::boolean = false
        OR d.id IS NOT NULL
    ) -- В наличии
    AND (
        $14::boolean IS NULL
        OR $14::boolean = false
        OR (
            sh.id IS NOT NULL
            AND sh.quantity > 0
        )
    ) -- Исключаем ID (если переданы)
    AND (
        COALESCE(array_length($15::int [], 1), 0) = 0
        OR p.id != ALL($15::int [])
    ) -- Цена > 0
    AND (
        $16::boolean IS NULL
        OR $16::boolean = false
        OR p.minprice > 0
    )
ORDER BY CASE
        WHEN $17::int = 1 THEN p.name
    END ASC,
    CASE
        WHEN $17::int = 2 THEN p.name
    END DESC,
    CASE
        WHEN $17::int = 3 THEN p.minprice
    END ASC,
    CASE
        WHEN $17::int = 4 THEN p.minprice
    END DESC,
    p.id ASC
LIMIT CASE
        WHEN $19::integer > 0 THEN $19::integer
        ELSE 50
    END OFFSET CASE
        WHEN $18::integer > 0 THEN $18::integer
        ELSE 0
    END
`

type GetProductIDsForAdminByFiltersParams struct {
	Status       string             `json:"status"`
	Sizes        []string           `json:"sizes"`
	Name         string             `json:"name"`
	Categories   []int32            `json:"categories"`
	ProductTypes []int32            `json:"product_types"`
	Firms        []int32            `json:"firms"`
	Lines        []int32            `json:"lines"`
	Bodytypes    []string           `json:"bodytypes"`
	Minprice     pgtype.Int4        `json:"minprice"`
	Maxprice     pgtype.Int4        `json:"maxprice"`
	CreatedFrom  pgtype.Timestamptz `json:"created_from"`
	UpdatedFrom  pgtype.Timestamptz `json:"updated_from"`
	HasDiscount  bool               `json:"has_discount"`
	InStore      bool               `json:"in_store"`
	ExcludeIds   []int32            `json:"exclude_ids"`
	WithPrice    bool               `json:"with_price"`
	SortType     int32              `json:"sort_type"`
	Offsetval    int32              `json:"offsetval"`
	Limitval     int32              `json:"limitval"`
}

func (q *Queries) GetProductIDsForAdminByFilters(ctx context.Context, arg GetProductIDsForAdminByFiltersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getProductIDsForAdminByFilters,
		arg.Status,
		arg.Sizes,
		arg.Name,
		arg.Categories,
		arg.ProductTypes,
		arg.Firms,
		arg.Lines,
		arg.Bodytypes,
		arg.Minprice,
		arg.Maxprice,
		arg.CreatedFrom,
		arg.UpdatedFrom,
		arg.HasDiscount,
		arg.InStore,
		arg.ExcludeIds,
		arg.WithPrice,
		arg.SortType,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsForAdminByFilters = `-- name: GetProductsForAdminByFilters :many
SELECT p.id,
    p.name,
    p.image_path,
    b.name AS firm,
    p.type,
    p.category,
    p.minprice,
    p.maxprice,
    p.status,
    p.updated_at,
    -- Итоговый процент скидки: максимальный процент из всех размеров в discount
    COALESCE(
        (
            SELECT MAX((item.value->>'value')::int)
            FROM jsonb_each(d.value) AS item
            WHERE item.value->>'type' = 'percentage'
        ),
        0
    ) AS discount_percent,
    COUNT(*) FILTER (
        WHERE p.status = 'active'
    ) OVER() AS active_count,
    COUNT(*) OVER() AS total_count
FROM products p
    JOIN brands b ON p.brand_id = b.id
    LEFT JOIN brand_lines bl ON p.line_id = bl.id
    LEFT JOIN store_house sh ON p.id = sh.productid
    LEFT JOIN discount d ON p.id = d.productid
WHERE p.status != 'deleted' -- Статус
    AND (
        $1::text IS NULL
        OR $1::text = ''
        OR p.status = $1::text
    ) -- Размеры
    AND (
        COALESCE(array_length($2::text [], 1), 0) = 0
        OR EXISTS (
            SELECT 1
            FROM jsonb_object_keys(p.sizes) AS size_key
            WHERE size_key = ANY($2::text [])
                AND (p.sizes->size_key->>'price')::numeric > 0
        )
    ) -- Поиск
    AND (
        $3::text IS NULL
        OR $3::text = ''
        OR p.name ILIKE '%' || $3::text || '%'
        OR p.article ILIKE '%' || $3::text || '%'
    ) -- Категории
    AND (
        COALESCE(array_length($4::int [], 1), 0) = 0
        OR p.category = ANY($4::int [])
    ) -- Типы
    AND (
        COALESCE(array_length($5::int [], 1), 0) = 0
        OR p.type = ANY($5::int [])
    ) -- Фирмы
    AND (
        COALESCE(array_length($6::int [], 1), 0) = 0
        OR p.brand_id = ANY($6::int [])
    ) -- Линии
    AND (
        COALESCE(array_length($7::int [], 1), 0) = 0
        OR p.line_id = ANY($7::int [])
    ) -- Типы тела
    AND (
        COALESCE(array_length($8::text [], 1), 0) = 0
        OR p.bodytype = ANY($8::body_enum [])
    ) -- Цены
    AND (
        $9::int IS NULL
        OR p.maxprice >= $9::int
    )
    AND (
        $10::int IS NULL
        OR p.minprice <= $10::int
    )
    AND (
        $11::timestamptz IS NULL
        OR p.created_at >= $11::timestamptz
    )
    AND (
        $12::timestamptz IS NULL
        OR p.updated_at >= $12::timestamptz
    ) -- Скидка (наличие)
    AND (
        $13::boolean IS NULL
        OR $13::boolean = false
        OR d.productid IS NOT NULL
    ) -- В наличии
    AND (
        $14::boolean IS NULL
        OR $14::boolean = false
        OR (
            sh.id IS NOT NULL
            AND sh.quantity > 0
        )
    ) -- Цена > 0
    AND (
        $15::boolean IS NULL
        OR $15::boolean = false
        OR p.minprice > 0
    )
ORDER BY -- Сортировка по имени
    CASE
        WHEN $16::int = 1 THEN p.name
    END ASC,
    CASE
        WHEN $16::int = 2 THEN p.name
    END DESC,
    -- Сортировка по цене
    CASE
        WHEN $16::int = 3 THEN p.minprice
    END ASC,
    CASE
        WHEN $16::int = 4 THEN p.minprice
    END DESC,
    -- Сортировка по бренду
    CASE
        WHEN $16::int = 5 THEN b.name
    END ASC,
    CASE
        WHEN $16::int = 6 THEN b.name
    END DESC,
    -- Сортировка по скидке
    CASE
        WHEN $16::int = 7 THEN COALESCE(
            (
                SELECT MAX((item.value->>'value')::int)
                FROM jsonb_each(d.value) AS item
                WHERE item.value->>'type' = 'percentage'
            ),
            0
        )
    END ASC,
    CASE
        WHEN $16::int = 8 THEN COALESCE(
            (
                SELECT MAX((item.value->>'value')::int)
                FROM jsonb_each(d.value) AS item
                WHERE item.value->>'type' = 'percentage'
            ),
            0
        )
    END DESC,
    -- Сортировка по дате создания
    CASE
        WHEN $16::int = 9 THEN p.created_at
    END ASC,
    CASE
        WHEN $16::int = 10 THEN p.created_at
    END DESC,
    -- Сортировка по дате обновления
    CASE
        WHEN $16::int = 11 THEN p.updated_at
    END ASC NULLS LAST,
    CASE
        WHEN $16::int = 12 THEN p.updated_at
    END DESC NULLS LAST,
    -- Сортировка по статусу
    CASE
        WHEN $16::int = 13 THEN p.status
    END ASC,
    CASE
        WHEN $16::int = 14 THEN p.status
    END DESC,
    -- Вторичная сортировка по id для стабильности
    p.id ASC
LIMIT CASE
        WHEN $18::integer > 0 THEN $18::integer
        ELSE 50
    END OFFSET CASE
        WHEN $17::integer > 0 THEN $17::integer
        ELSE 0
    END
`

type GetProductsForAdminByFiltersParams struct {
	Status       string             `json:"status"`
	Sizes        []string           `json:"sizes"`
	Name         string             `json:"name"`
	Categories   []int32            `json:"categories"`
	ProductTypes []int32            `json:"product_types"`
	Firms        []int32            `json:"firms"`
	Lines        []int32            `json:"lines"`
	Bodytypes    []string           `json:"bodytypes"`
	Minprice     pgtype.Int4        `json:"minprice"`
	Maxprice     pgtype.Int4        `json:"maxprice"`
	CreatedFrom  pgtype.Timestamptz `json:"created_from"`
	UpdatedFrom  pgtype.Timestamptz `json:"updated_from"`
	HasDiscount  bool               `json:"has_discount"`
	InStore      bool               `json:"in_store"`
	WithPrice    bool               `json:"with_price"`
	SortType     int32              `json:"sort_type"`
	Offsetval    int32              `json:"offsetval"`
	Limitval     int32              `json:"limitval"`
}

type GetProductsForAdminByFiltersRow struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	ImagePath       string             `json:"image_path"`
	Firm            string             `json:"firm"`
	Type            int32              `json:"type"`
	Category        int32              `json:"category"`
	Minprice        int32              `json:"minprice"`
	Maxprice        int32              `json:"maxprice"`
	Status          string             `json:"status"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DiscountPercent interface{}        `json:"discount_percent"`
	ActiveCount     int64              `json:"active_count"`
	TotalCount      int64              `json:"total_count"`
}

func (q *Queries) GetProductsForAdminByFilters(ctx context.Context, arg GetProductsForAdminByFiltersParams) ([]GetProductsForAdminByFiltersRow, error) {
	rows, err := q.db.Query(ctx, getProductsForAdminByFilters,
		arg.Status,
		arg.Sizes,
		arg.Name,
		arg.Categories,
		arg.ProductTypes,
		arg.Firms,
		arg.Lines,
		arg.Bodytypes,
		arg.Minprice,
		arg.Maxprice,
		arg.CreatedFrom,
		arg.UpdatedFrom,
		arg.HasDiscount,
		arg.InStore,
		arg.WithPrice,
		arg.SortType,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsForAdminByFiltersRow
	for rows.Next() {
		var i GetProductsForAdminByFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImagePath,
			&i.Firm,
			&i.Type,
			&i.Category,
			&i.Minprice,
			&i.Maxprice,
			&i.Status,
			&i.UpdatedAt,
			&i.DiscountPercent,
			&i.ActiveCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductsWithSizesByIDs = `-- name: GetProductsWithSizesByIDs :many
SELECT p.id,
    p.sizes,
    p.minprice,
    p.maxprice
FROM products p
WHERE p.id = ANY($1::int [])
    AND p.status != 'deleted'
`

type GetProductsWithSizesByIDsRow struct {
	ID       int32  `json:"id"`
	Sizes    []byte `json:"sizes"`
	Minprice int32  `json:"minprice"`
	Maxprice int32  `json:"maxprice"`
}

func (q *Queries) GetProductsWithSizesByIDs(ctx context.Context, productIds []int32) ([]GetProductsWithSizesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProductsWithSizesByIDs, productIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsWithSizesByIDsRow
	for rows.Next() {
		var i GetProductsWithSizesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sizes,
			&i.Minprice,
			&i.Maxprice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentActivity = `-- name: GetRecentActivity :many
SELECT al.id,
    al.action,
    al.entity_type,
    al.entity_id,
    al.created_at,
    a.name as admin_name
FROM admin_logs al
    JOIN admins a ON al.admin_id = a.id
ORDER BY al.created_at DESC
LIMIT 20
`

type GetRecentActivityRow struct {
	ID         int32              `json:"id"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Int4        `json:"entity_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AdminName  string             `json:"admin_name"`
}

func (q *Queries) GetRecentActivity(ctx context.Context) ([]GetRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, getRecentActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentActivityRow
	for rows.Next() {
		var i GetRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentOrders = `-- name: GetRecentOrders :many
SELECT o.id,
    o.orderdate,
    o.status,
    o.deliverytype,
    COALESCE(c.name, uc.name)::text as customer_name,
    (
        SELECT COALESCE(SUM(oi.quantity * oi.price), 0)
        FROM orderitems oi
        WHERE oi.orderid = o.id
    ) as total_amount
FROM orders o
    LEFT JOIN customers c ON o.customerid = c.id
    LEFT JOIN unregistercustomer uc ON o.unregistercustomerid = uc.id
ORDER BY o.created_at DESC
LIMIT 10
`

type GetRecentOrdersRow struct {
	ID           int32        `json:"id"`
	Orderdate    pgtype.Date  `json:"orderdate"`
	Status       StatusEnum   `json:"status"`
	Deliverytype DeliveryEnum `json:"deliverytype"`
	CustomerName string       `json:"customer_name"`
	TotalAmount  interface{}  `json:"total_amount"`
}

func (q *Queries) GetRecentOrders(ctx context.Context) ([]GetRecentOrdersRow, error) {
	rows, err := q.db.Query(ctx, getRecentOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentOrdersRow
	for rows.Next() {
		var i GetRecentOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Orderdate,
			&i.Status,
			&i.Deliverytype,
			&i.CustomerName,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnregisterCustomersCount = `-- name: GetUnregisterCustomersCount :one
SELECT COUNT(*)
FROM unregistercustomer
`

func (q *Queries) GetUnregisterCustomersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUnregisterCustomersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnregisterCustomersList = `-- name: GetUnregisterCustomersList :many
SELECT id,
    name,
    secondname,
    mail,
    phone,
    town,
    index,
    street,
    settlement,
    region,
    house,
    flat,
    created_at,
    (
        SELECT COUNT(*)
        FROM orders o
        WHERE o.unregistercustomerid = uc.id
    ) as orders_count
FROM unregistercustomer uc
WHERE (
        $1::text IS NULL
        OR uc.name ILIKE '%' || $1 || '%'
        OR uc.mail ILIKE '%' || $1 || '%'
        OR uc.phone ILIKE '%' || $1 || '%'
    )
ORDER BY uc.created_at DESC
LIMIT $3 OFFSET $2
`

type GetUnregisterCustomersListParams struct {
	Search    pgtype.Text `json:"search"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

type GetUnregisterCustomersListRow struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Secondname  pgtype.Text      `json:"secondname"`
	Mail        string           `json:"mail"`
	Phone       string           `json:"phone"`
	Town        string           `json:"town"`
	Index       string           `json:"index"`
	Street      pgtype.Text      `json:"street"`
	Settlement  pgtype.Text      `json:"settlement"`
	Region      pgtype.Text      `json:"region"`
	House       pgtype.Text      `json:"house"`
	Flat        pgtype.Text      `json:"flat"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	OrdersCount int64            `json:"orders_count"`
}

func (q *Queries) GetUnregisterCustomersList(ctx context.Context, arg GetUnregisterCustomersListParams) ([]GetUnregisterCustomersListRow, error) {
	rows, err := q.db.Query(ctx, getUnregisterCustomersList, arg.Search, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnregisterCustomersListRow
	for rows.Next() {
		var i GetUnregisterCustomersListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Secondname,
			&i.Mail,
			&i.Phone,
			&i.Town,
			&i.Index,
			&i.Street,
			&i.Settlement,
			&i.Region,
			&i.House,
			&i.Flat,
			&i.CreatedAt,
			&i.OrdersCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdmins = `-- name: ListAdmins :many
SELECT id,
    email,
    name,
    role,
    is_active,
    last_login_at,
    created_at
FROM admins
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdminsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdminsRow struct {
	ID          int32              `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	Role        AdminRoleEnum      `json:"role"`
	IsActive    pgtype.Bool        `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context, arg ListAdminsParams) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminsRow
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAsUsed = `-- name: MarkInviteAsUsed :exec
UPDATE admin_invites
SET used_at = NOW(),
    used_by = $2,
    updated_at = NOW()
WHERE token = $1 
  AND used_at IS NULL 
  AND expires_at > NOW()
`

type MarkInviteAsUsedParams struct {
	Token  string      `json:"token"`
	UsedBy pgtype.Int4 `json:"used_by"`
}

func (q *Queries) MarkInviteAsUsed(ctx context.Context, arg MarkInviteAsUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteAsUsed, arg.Token, arg.UsedBy)
	return err
}

const updateAdmin = `-- name: UpdateAdmin :exec
UPDATE admins
SET name = COALESCE($1, name),
    role = COALESCE($2, role),
    is_active = COALESCE($3, is_active),
    updated_at = NOW()
WHERE id = $4
`

type UpdateAdminParams struct {
	Name     pgtype.Text       `json:"name"`
	Role     NullAdminRoleEnum `json:"role"`
	IsActive pgtype.Bool       `json:"is_active"`
	AdminID  int32             `json:"admin_id"`
}

func (q *Queries) UpdateAdmin(ctx context.Context, arg UpdateAdminParams) error {
	_, err := q.db.Exec(ctx, updateAdmin,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.AdminID,
	)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admins
SET last_login_at = NOW(),
    last_login_ip = $2
WHERE id = $1
`

type UpdateAdminLastLoginParams struct {
	ID          int32       `json:"id"`
	LastLoginIp *netip.Addr `json:"last_login_ip"`
}

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, arg UpdateAdminLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, arg.ID, arg.LastLoginIp)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admins
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           int32  `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAdminRole = `-- name: UpdateAdminRole :exec
UPDATE admins
SET role = $2
WHERE id = $1
`

type UpdateAdminRoleParams struct {
	ID   int32         `json:"id"`
	Role AdminRoleEnum `json:"role"`
}

func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminRole, arg.ID, arg.Role)
	return err
}

const updateAdminStatus = `-- name: UpdateAdminStatus :exec
UPDATE admins
SET is_active = $2
WHERE id = $1
`

type UpdateAdminStatusParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateAdminStatus(ctx context.Context, arg UpdateAdminStatusParams) error {
	_, err := q.db.Exec(ctx, updateAdminStatus, arg.ID, arg.IsActive)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1::status_enum
WHERE id = $2
`

type UpdateOrderStatusParams struct {
	Status  StatusEnum `json:"status"`
	OrderID int32      `json:"order_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.OrderID)
	return err
}

const updateProductPrice = `-- name: UpdateProductPrice :exec
UPDATE products
SET sizes = $1::jsonb,
    minprice = $2::int,
    maxprice = $3::int,
    updated_at = NOW()
WHERE id = $4::int
`

type UpdateProductPriceParams struct {
	Sizes    []byte `json:"sizes"`
	Minprice int32  `json:"minprice"`
	Maxprice int32  `json:"maxprice"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) error {
	_, err := q.db.Exec(ctx, updateProductPrice,
		arg.Sizes,
		arg.Minprice,
		arg.Maxprice,
		arg.ID,
	)
	return err
}
