// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: discount.sql

package db

import (
	"context"
)

const restoreDiscounts = `-- name: RestoreDiscounts :exec
DELETE FROM discount
WHERE min_price = 0
`

func (q *Queries) RestoreDiscounts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, restoreDiscounts)
	return err
}
