// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: main.sql

package db

import (
	"context"
)

const getMainPageBanners = `-- name: GetMainPageBanners :many
SELECT 
    id,
    title,
    subtitle,
    description,
    image_url,
    button_text,
    button_url
FROM homepage_blocks
ORDER BY id ASC
`

func (q *Queries) GetMainPageBanners(ctx context.Context) ([]HomepageBlock, error) {
	rows, err := q.db.Query(ctx, getMainPageBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomepageBlock
	for rows.Next() {
		var i HomepageBlock
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Subtitle,
			&i.Description,
			&i.ImageUrl,
			&i.ButtonText,
			&i.ButtonUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
