// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AdminRoleEnum string

const (
	AdminRoleEnumAdmin      AdminRoleEnum = "admin"
	AdminRoleEnumSuperadmin AdminRoleEnum = "superadmin"
)

func (e *AdminRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRoleEnum(s)
	case string:
		*e = AdminRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRoleEnum: %T", src)
	}
	return nil
}

type NullAdminRoleEnum struct {
	AdminRoleEnum AdminRoleEnum `json:"admin_role_enum"`
	Valid         bool          `json:"valid"` // Valid is true if AdminRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRoleEnum), nil
}

type BodyEnum string

const (
	BodyEnumChild  BodyEnum = "child"
	BodyEnumWoman  BodyEnum = "woman"
	BodyEnumMan    BodyEnum = "man"
	BodyEnumUnisex BodyEnum = "unisex"
)

func (e *BodyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BodyEnum(s)
	case string:
		*e = BodyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BodyEnum: %T", src)
	}
	return nil
}

type NullBodyEnum struct {
	BodyEnum BodyEnum `json:"body_enum"`
	Valid    bool     `json:"valid"` // Valid is true if BodyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBodyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BodyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BodyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBodyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BodyEnum), nil
}

type DeliveryEnum string

const (
	DeliveryEnumOwn     DeliveryEnum = "own"
	DeliveryEnumExpress DeliveryEnum = "express"
	DeliveryEnumCdek    DeliveryEnum = "cdek"
	DeliveryEnumCurier  DeliveryEnum = "curier"
)

func (e *DeliveryEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryEnum(s)
	case string:
		*e = DeliveryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryEnum: %T", src)
	}
	return nil
}

type NullDeliveryEnum struct {
	DeliveryEnum DeliveryEnum `json:"delivery_enum"`
	Valid        bool         `json:"valid"` // Valid is true if DeliveryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryEnum), nil
}

type StatusEnum string

const (
	StatusEnumPending  StatusEnum = "pending"
	StatusEnumApproved StatusEnum = "approved"
	StatusEnumRejected StatusEnum = "rejected"
)

func (e *StatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusEnum(s)
	case string:
		*e = StatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusEnum: %T", src)
	}
	return nil
}

type NullStatusEnum struct {
	StatusEnum StatusEnum `json:"status_enum"`
	Valid      bool       `json:"valid"` // Valid is true if StatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusEnum), nil
}

type Admin struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash []byte             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         AdminRoleEnum      `json:"role"`
	IsActive     pgtype.Bool        `json:"is_active"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	LastLoginIp  *netip.Addr        `json:"last_login_ip"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AdminInvite struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Role      AdminRoleEnum      `json:"role"`
	Token     string             `json:"token"`
	InvitedBy pgtype.Int4        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	UsedBy    pgtype.Int4        `json:"used_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AdminLog struct {
	ID         int32              `json:"id"`
	AdminID    int32              `json:"admin_id"`
	Action     string             `json:"action"`
	EntityType pgtype.Text        `json:"entity_type"`
	EntityID   pgtype.Int4        `json:"entity_id"`
	Details    pgtype.Text        `json:"details"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AdminPasswordReset struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Banner struct {
	ID        int32              `json:"id"`
	Title     pgtype.Text        `json:"title"`
	ImageUrl  string             `json:"image_url"`
	LinkUrl   string             `json:"link_url"`
	IsActive  bool               `json:"is_active"`
	SortOrder pgtype.Int4        `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Brand struct {
	ID          int32              `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	ImagePath   pgtype.Text        `json:"image_path"`
	Description pgtype.Text        `json:"description"`
	Website     pgtype.Text        `json:"website"`
	Country     pgtype.Text        `json:"country"`
	SortOrder   int32              `json:"sort_order"`
	FoundedYear pgtype.Int4        `json:"founded_year"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BrandLine struct {
	ID          int32              `json:"id"`
	BrandID     int32              `json:"brand_id"`
	Name        string             `json:"name"`
	ImagePath   pgtype.Text        `json:"image_path"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	Season      pgtype.Text        `json:"season"`
	Year        pgtype.Int4        `json:"year"`
	SortOrder   pgtype.Int4        `json:"sort_order"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BrandsStat struct {
	BrandID          int32            `json:"brand_id"`
	TotalProducts    pgtype.Int4      `json:"total_products"`
	ActiveProducts   pgtype.Int4      `json:"active_products"`
	InactiveProducts pgtype.Int4      `json:"inactive_products"`
	SneakersCount    pgtype.Int4      `json:"sneakers_count"`
	MerchCount       pgtype.Int4      `json:"merch_count"`
	ClothesCount     pgtype.Int4      `json:"clothes_count"`
	ToysCount        pgtype.Int4      `json:"toys_count"`
	LinesCount       pgtype.Int4      `json:"lines_count"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

type Color struct {
	ID      int32  `json:"id"`
	EnumKey string `json:"enum_key"`
	Name    string `json:"name"`
	HexCode string `json:"hex_code"`
}

type Customer struct {
	ID          int32              `json:"id"`
	Name        pgtype.Text        `json:"name"`
	Secondname  pgtype.Text        `json:"secondname"`
	Mail        string             `json:"mail"`
	Pass        []byte             `json:"pass"`
	Phone       pgtype.Text        `json:"phone"`
	Town        pgtype.Text        `json:"town"`
	Index       pgtype.Text        `json:"index"`
	Sendmail    pgtype.Bool        `json:"sendmail"`
	Street      pgtype.Text        `json:"street"`
	Region      pgtype.Text        `json:"region"`
	Home        pgtype.Text        `json:"home"`
	Flat        pgtype.Text        `json:"flat"`
	Coordinates []int32            `json:"coordinates"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CustomerPasswordReset struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Discount struct {
	ID           int32              `json:"id"`
	Productid    int32              `json:"productid"`
	Value        []byte             `json:"value"`
	Minprice     int32              `json:"minprice"`
	Maxdiscprice pgtype.Int4        `json:"maxdiscprice"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DiscountRule struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	DiscountType  string             `json:"discount_type"`
	DiscountValue int32              `json:"discount_value"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	IsActive      bool               `json:"is_active"`
	Priority      int32              `json:"priority"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type DiscountRuleItem struct {
	ID       int32  `json:"id"`
	RuleID   int32  `json:"rule_id"`
	ItemType string `json:"item_type"`
	ItemID   int32  `json:"item_id"`
}

type NewsletterSubscriber struct {
	ID                int32            `json:"id"`
	Email             string           `json:"email"`
	Status            string           `json:"status"`
	VerificationToken string           `json:"verification_token"`
	TokenExpiresAt    pgtype.Timestamp `json:"token_expires_at"`
	VerifiedAt        pgtype.Timestamp `json:"verified_at"`
	SubscribedAt      pgtype.Timestamp `json:"subscribed_at"`
	IpAddress         pgtype.Text      `json:"ip_address"`
	UserAgent         pgtype.Text      `json:"user_agent"`
}

type Order struct {
	ID                   int32              `json:"id"`
	Customerid           pgtype.Int4        `json:"customerid"`
	Unregistercustomerid pgtype.Int4        `json:"unregistercustomerid"`
	Orderdate            pgtype.Date        `json:"orderdate"`
	Status               StatusEnum         `json:"status"`
	Hash                 string             `json:"hash"`
	Deliveryprice        int32              `json:"deliveryprice"`
	Deliverycomment      pgtype.Text        `json:"deliverycomment"`
	Deliverytype         DeliveryEnum       `json:"deliverytype"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type OrderEvent struct {
	ID             int64              `json:"id"`
	OrderID        int32              `json:"order_id"`
	EventType      string             `json:"event_type"`
	OldStatus      pgtype.Text        `json:"old_status"`
	NewStatus      pgtype.Text        `json:"new_status"`
	Reason         pgtype.Text        `json:"reason"`
	ReasonCode     pgtype.Text        `json:"reason_code"`
	ChangedByAdmin pgtype.Int4        `json:"changed_by_admin"`
	ChangedByType  string             `json:"changed_by_type"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Orderaddress struct {
	ID              int32       `json:"id"`
	Orderid         int32       `json:"orderid"`
	Town            string      `json:"town"`
	Index           string      `json:"index"`
	Sendmail        pgtype.Bool `json:"sendmail"`
	Street          pgtype.Text `json:"street"`
	Region          pgtype.Text `json:"region"`
	Deliverycomment pgtype.Text `json:"deliverycomment"`
	House           pgtype.Text `json:"house"`
	Flat            pgtype.Text `json:"flat"`
	Coordinates     []string    `json:"coordinates"`
}

type Orderitem struct {
	ID        int32       `json:"id"`
	Orderid   int32       `json:"orderid"`
	Productid int32       `json:"productid"`
	Quantity  int32       `json:"quantity"`
	Price     int32       `json:"price"`
	ImagePath string      `json:"image_path"`
	Name      string      `json:"name"`
	Size      pgtype.Text `json:"size"`
}

type PageWidget struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	SortOrder int32       `json:"sort_order"`
	IsActive  pgtype.Bool `json:"is_active"`
	Settings  []byte      `json:"settings"`
	LinkUrl   string      `json:"link_url"`
}

type PasswordReset struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	UserType  string             `json:"user_type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Preorder struct {
	ID         int32       `json:"id"`
	Hashurl    string      `json:"hashurl"`
	Updatetime pgtype.Date `json:"updatetime"`
}

type Preorderaddress struct {
	ID          int32       `json:"id"`
	Town        string      `json:"town"`
	Index       string      `json:"index"`
	Sendmail    pgtype.Bool `json:"sendmail"`
	Street      pgtype.Text `json:"street"`
	Region      pgtype.Text `json:"region"`
	House       pgtype.Text `json:"house"`
	Orderid     int32       `json:"orderid"`
	Flat        pgtype.Text `json:"flat"`
	Coordinates []string    `json:"coordinates"`
}

type Preorderitem struct {
	ID        int32       `json:"id"`
	Orderid   int32       `json:"orderid"`
	Productid int32       `json:"productid"`
	Quantity  int32       `json:"quantity"`
	Price     int32       `json:"price"`
	ImagePath string      `json:"image_path"`
	Name      string      `json:"name"`
	Size      pgtype.Text `json:"size"`
}

type Product struct {
	ID          int32              `json:"id"`
	Qid         string             `json:"qid"`
	Name        string             `json:"name"`
	ImagePath   string             `json:"image_path"`
	Minprice    int32              `json:"minprice"`
	Maxprice    int32              `json:"maxprice"`
	Type        int32              `json:"type"`
	Category    int32              `json:"category"`
	Article     string             `json:"article"`
	Date        pgtype.Text        `json:"date"`
	Description pgtype.Text        `json:"description"`
	Bodytype    BodyEnum           `json:"bodytype"`
	ImageCount  int32              `json:"image_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Sizes       []byte             `json:"sizes"`
	BrandID     int32              `json:"brand_id"`
	LineID      pgtype.Int4        `json:"line_id"`
	Status      string             `json:"status"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type ProductCategory struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	EnumKey   string      `json:"enum_key"`
	ImagePath pgtype.Text `json:"image_path"`
}

type ProductColor struct {
	ProductID int32 `json:"product_id"`
	ColorID   int32 `json:"color_id"`
}

type ProductType struct {
	ID         int32  `json:"id"`
	CategoryID int32  `json:"category_id"`
	TypeName   string `json:"type_name"`
	EnumKey    string `json:"enum_key"`
}

type StoreHouse struct {
	ID        int32              `json:"id"`
	Productid int32              `json:"productid"`
	Size      string             `json:"size"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Uniquecustomer struct {
	ID           int32       `json:"id"`
	Creationtime pgtype.Date `json:"creationtime"`
	History      []int32     `json:"history"`
}

type Unregistercustomer struct {
	ID              int32            `json:"id"`
	Name            string           `json:"name"`
	Secondname      pgtype.Text      `json:"secondname"`
	Mail            string           `json:"mail"`
	Phone           string           `json:"phone"`
	Town            string           `json:"town"`
	Index           string           `json:"index"`
	Sendmail        pgtype.Bool      `json:"sendmail"`
	Street          pgtype.Text      `json:"street"`
	Settlement      pgtype.Text      `json:"settlement"`
	Region          pgtype.Text      `json:"region"`
	Deliverycomment pgtype.Text      `json:"deliverycomment"`
	House           pgtype.Text      `json:"house"`
	Flat            pgtype.Text      `json:"flat"`
	Coordinates     []string         `json:"coordinates"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Verification struct {
	ID         int32            `json:"id"`
	Token      string           `json:"token"`
	Customerid int32            `json:"customerid"`
	Expire     pgtype.Timestamp `json:"expire"`
	Deletetime pgtype.Timestamp `json:"deletetime"`
}
