// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BodyEnum string

const (
	BodyEnumChild BodyEnum = "child"
	BodyEnumWoman BodyEnum = "woman"
	BodyEnumMan   BodyEnum = "man"
)

func (e *BodyEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BodyEnum(s)
	case string:
		*e = BodyEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for BodyEnum: %T", src)
	}
	return nil
}

type NullBodyEnum struct {
	BodyEnum BodyEnum `json:"body_enum"`
	Valid    bool     `json:"valid"` // Valid is true if BodyEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBodyEnum) Scan(value interface{}) error {
	if value == nil {
		ns.BodyEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BodyEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBodyEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BodyEnum), nil
}

type ClothesEnum string

const (
	ClothesEnumTShirt     ClothesEnum = "t-shirt"
	ClothesEnumHoodie     ClothesEnum = "hoodie"
	ClothesEnumSweatshirt ClothesEnum = "sweatshirt"
	ClothesEnumJacket     ClothesEnum = "jacket"
	ClothesEnumPants      ClothesEnum = "pants"
	ClothesEnumShorts     ClothesEnum = "shorts"
	ClothesEnumOther      ClothesEnum = "other"
)

func (e *ClothesEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClothesEnum(s)
	case string:
		*e = ClothesEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ClothesEnum: %T", src)
	}
	return nil
}

type NullClothesEnum struct {
	ClothesEnum ClothesEnum `json:"clothes_enum"`
	Valid       bool        `json:"valid"` // Valid is true if ClothesEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClothesEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ClothesEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClothesEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClothesEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClothesEnum), nil
}

type DeliveryEnum string

const (
	DeliveryEnumOwn     DeliveryEnum = "own"
	DeliveryEnumExpress DeliveryEnum = "express"
	DeliveryEnumCdek    DeliveryEnum = "cdek"
	DeliveryEnumCurier  DeliveryEnum = "curier"
)

func (e *DeliveryEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryEnum(s)
	case string:
		*e = DeliveryEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryEnum: %T", src)
	}
	return nil
}

type NullDeliveryEnum struct {
	DeliveryEnum DeliveryEnum `json:"delivery_enum"`
	Valid        bool         `json:"valid"` // Valid is true if DeliveryEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryEnum) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryEnum), nil
}

type MerchEnum string

const (
	MerchEnumHat   MerchEnum = "hat"
	MerchEnumToys  MerchEnum = "toys"
	MerchEnumBag   MerchEnum = "bag"
	MerchEnumOther MerchEnum = "other"
)

func (e *MerchEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MerchEnum(s)
	case string:
		*e = MerchEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MerchEnum: %T", src)
	}
	return nil
}

type NullMerchEnum struct {
	MerchEnum MerchEnum `json:"merch_enum"`
	Valid     bool      `json:"valid"` // Valid is true if MerchEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMerchEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MerchEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MerchEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMerchEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MerchEnum), nil
}

type ProductSourceEnum string

const (
	ProductSourceEnumSnickers  ProductSourceEnum = "snickers"
	ProductSourceEnumSolomerch ProductSourceEnum = "solomerch"
	ProductSourceEnumClothes   ProductSourceEnum = "clothes"
)

func (e *ProductSourceEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductSourceEnum(s)
	case string:
		*e = ProductSourceEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductSourceEnum: %T", src)
	}
	return nil
}

type NullProductSourceEnum struct {
	ProductSourceEnum ProductSourceEnum `json:"product_source_enum"`
	Valid             bool              `json:"valid"` // Valid is true if ProductSourceEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductSourceEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProductSourceEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductSourceEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductSourceEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductSourceEnum), nil
}

type SnickersEnum string

const (
	SnickersEnumSlepowers SnickersEnum = "slepowers"
	SnickersEnumOther     SnickersEnum = "other"
)

func (e *SnickersEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SnickersEnum(s)
	case string:
		*e = SnickersEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for SnickersEnum: %T", src)
	}
	return nil
}

type NullSnickersEnum struct {
	SnickersEnum SnickersEnum `json:"snickers_enum"`
	Valid        bool         `json:"valid"` // Valid is true if SnickersEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSnickersEnum) Scan(value interface{}) error {
	if value == nil {
		ns.SnickersEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SnickersEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSnickersEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SnickersEnum), nil
}

type StatusEnum string

const (
	StatusEnumPending  StatusEnum = "pending"
	StatusEnumApproved StatusEnum = "approved"
	StatusEnumRejected StatusEnum = "rejected"
)

func (e *StatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusEnum(s)
	case string:
		*e = StatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusEnum: %T", src)
	}
	return nil
}

type NullStatusEnum struct {
	StatusEnum StatusEnum `json:"status_enum"`
	Valid      bool       `json:"valid"` // Valid is true if StatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusEnum), nil
}

type Color struct {
	ID      int32  `json:"id"`
	EnumKey string `json:"enum_key"`
	Name    string `json:"name"`
	HexCode string `json:"hex_code"`
}

type Customer struct {
	ID          int32       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Secondname  pgtype.Text `json:"secondname"`
	Mail        string      `json:"mail"`
	Pass        []byte      `json:"pass"`
	Phone       pgtype.Text `json:"phone"`
	Town        pgtype.Text `json:"town"`
	Index       pgtype.Text `json:"index"`
	Sendmail    pgtype.Bool `json:"sendmail"`
	Street      pgtype.Text `json:"street"`
	Region      pgtype.Text `json:"region"`
	Home        pgtype.Text `json:"home"`
	Flat        pgtype.Text `json:"flat"`
	Coordinates []int32     `json:"coordinates"`
}

type Discount struct {
	ID           int32              `json:"id"`
	Productid    int32              `json:"productid"`
	Value        []byte             `json:"value"`
	Minprice     int32              `json:"minprice"`
	Maxdiscprice pgtype.Int4        `json:"maxdiscprice"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID                   int32        `json:"id"`
	Customerid           pgtype.Int4  `json:"customerid"`
	Unregistercustomerid pgtype.Int4  `json:"unregistercustomerid"`
	Orderdate            pgtype.Date  `json:"orderdate"`
	Status               StatusEnum   `json:"status"`
	Hash                 string       `json:"hash"`
	Deliveryprice        int32        `json:"deliveryprice"`
	Deliverytype         DeliveryEnum `json:"deliverytype"`
}

type Orderaddress struct {
	ID          int32       `json:"id"`
	Town        string      `json:"town"`
	Index       string      `json:"index"`
	Sendmail    pgtype.Bool `json:"sendmail"`
	Street      pgtype.Text `json:"street"`
	Region      pgtype.Text `json:"region"`
	House       pgtype.Text `json:"house"`
	Orderid     int32       `json:"orderid"`
	Flat        pgtype.Text `json:"flat"`
	Coordinates []string    `json:"coordinates"`
}

type Orderitem struct {
	ID        int32       `json:"id"`
	Orderid   int32       `json:"orderid"`
	Productid int32       `json:"productid"`
	Quantity  int32       `json:"quantity"`
	Price     int32       `json:"price"`
	ImagePath string      `json:"image_path"`
	Name      string      `json:"name"`
	Size      pgtype.Text `json:"size"`
}

type Preorder struct {
	ID         int32       `json:"id"`
	Hashurl    string      `json:"hashurl"`
	Updatetime pgtype.Date `json:"updatetime"`
}

type Preorderaddress struct {
	ID          int32       `json:"id"`
	Town        string      `json:"town"`
	Index       string      `json:"index"`
	Sendmail    pgtype.Bool `json:"sendmail"`
	Street      pgtype.Text `json:"street"`
	Region      pgtype.Text `json:"region"`
	House       pgtype.Text `json:"house"`
	Orderid     int32       `json:"orderid"`
	Flat        pgtype.Text `json:"flat"`
	Coordinates []string    `json:"coordinates"`
}

type Preorderitem struct {
	ID        int32       `json:"id"`
	Orderid   int32       `json:"orderid"`
	Productid int32       `json:"productid"`
	Quantity  int32       `json:"quantity"`
	Price     int32       `json:"price"`
	ImagePath string      `json:"image_path"`
	Name      string      `json:"name"`
	Size      pgtype.Text `json:"size"`
}

type Product struct {
	ID          int32       `json:"id"`
	Qid         string      `json:"qid"`
	Name        string      `json:"name"`
	Firm        string      `json:"firm"`
	Line        string      `json:"line"`
	ImagePath   string      `json:"image_path"`
	Minprice    int32       `json:"minprice"`
	Maxprice    int32       `json:"maxprice"`
	Type        int32       `json:"type"`
	Category    int32       `json:"category"`
	Article     string      `json:"article"`
	Date        pgtype.Text `json:"date"`
	Description pgtype.Text `json:"description"`
	Bodytype    BodyEnum    `json:"bodytype"`
	ImageCount  int32       `json:"image_count"`
	Sizes       []byte      `json:"sizes"`
}

type ProductCategory struct {
	ID        int32       `json:"id"`
	ImagePath pgtype.Text `json:"image_path"`
	Name      string      `json:"name"`
	EnumKey   string      `json:"enum_key"`
}

type ProductColor struct {
	ProductID int32 `json:"product_id"`
	ColorID   int32 `json:"color_id"`
}

type ProductType struct {
	ID         int32  `json:"id"`
	CategoryID int32  `json:"category_id"`
	TypeName   string `json:"type_name"`
	EnumKey    string `json:"enum_key"`
}

type StoreHouse struct {
	ID        int32              `json:"id"`
	Productid int32              `json:"productid"`
	Size      string             `json:"size"`
	Quantity  int32              `json:"quantity"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Uniquecustomer struct {
	ID           int32       `json:"id"`
	Creationtime pgtype.Date `json:"creationtime"`
	History      []int32     `json:"history"`
}

type Unregistercustomer struct {
	ID         int32       `json:"id"`
	Name       string      `json:"name"`
	Secondname pgtype.Text `json:"secondname"`
	Mail       string      `json:"mail"`
	Phone      string      `json:"phone"`
}

type Verification struct {
	ID         int32            `json:"id"`
	Token      string           `json:"token"`
	Customerid int32            `json:"customerid"`
	Expire     pgtype.Timestamp `json:"expire"`
	Deletetime pgtype.Timestamp `json:"deletetime"`
}
