// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: news.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveNewsBlocks = `-- name: CountActiveNewsBlocks :one
SELECT COUNT(*) FROM news_blocks WHERE is_active = true
`

func (q *Queries) CountActiveNewsBlocks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveNewsBlocks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNewsBlock = `-- name: CreateNewsBlock :one
INSERT INTO news_blocks (
    title, cover_image_url, cover_alt_text, 
    is_active, published_at, sort_order
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order
`

type CreateNewsBlockParams struct {
	Title         string             `json:"title"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	CoverAltText  pgtype.Text        `json:"cover_alt_text"`
	IsActive      pgtype.Bool        `json:"is_active"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	SortOrder     pgtype.Int4        `json:"sort_order"`
}

func (q *Queries) CreateNewsBlock(ctx context.Context, arg CreateNewsBlockParams) (NewsBlock, error) {
	row := q.db.QueryRow(ctx, createNewsBlock,
		arg.Title,
		arg.CoverImageUrl,
		arg.CoverAltText,
		arg.IsActive,
		arg.PublishedAt,
		arg.SortOrder,
	)
	var i NewsBlock
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverImageUrl,
		&i.CoverAltText,
		&i.IsActive,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewsCount,
		&i.LikesCount,
		&i.SortOrder,
	)
	return i, err
}

const createNewsItem = `-- name: CreateNewsItem :one
INSERT INTO news_items (
    news_block_id, item_type, content, image_url, link_url, layout, sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, news_block_id, item_type, content, image_url, link_url, layout, sort_order, created_at, updated_at
`

type CreateNewsItemParams struct {
	NewsBlockID int32            `json:"news_block_id"`
	ItemType    NewsItemTypeEnum `json:"item_type"`
	Content     pgtype.Text      `json:"content"`
	ImageUrl    pgtype.Text      `json:"image_url"`
	LinkUrl     pgtype.Text      `json:"link_url"`
	Layout      pgtype.Text      `json:"layout"`
	SortOrder   pgtype.Int4      `json:"sort_order"`
}

func (q *Queries) CreateNewsItem(ctx context.Context, arg CreateNewsItemParams) (NewsItem, error) {
	row := q.db.QueryRow(ctx, createNewsItem,
		arg.NewsBlockID,
		arg.ItemType,
		arg.Content,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.Layout,
		arg.SortOrder,
	)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.NewsBlockID,
		&i.ItemType,
		&i.Content,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Layout,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNewsBlock = `-- name: DeleteNewsBlock :exec
DELETE FROM news_blocks WHERE id = $1
`

func (q *Queries) DeleteNewsBlock(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNewsBlock, id)
	return err
}

const deleteNewsItem = `-- name: DeleteNewsItem :exec
DELETE FROM news_items WHERE id = $1
`

func (q *Queries) DeleteNewsItem(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNewsItem, id)
	return err
}

const deleteNewsItemsByBlock = `-- name: DeleteNewsItemsByBlock :exec
DELETE FROM news_items WHERE news_block_id = $1
`

func (q *Queries) DeleteNewsItemsByBlock(ctx context.Context, newsBlockID int32) error {
	_, err := q.db.Exec(ctx, deleteNewsItemsByBlock, newsBlockID)
	return err
}

const getActiveNewsBlocks = `-- name: GetActiveNewsBlocks :many
SELECT id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order FROM news_blocks 
WHERE is_active = true 
ORDER BY sort_order ASC, id ASC
LIMIT 10
`

func (q *Queries) GetActiveNewsBlocks(ctx context.Context) ([]NewsBlock, error) {
	rows, err := q.db.Query(ctx, getActiveNewsBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsBlock
	for rows.Next() {
		var i NewsBlock
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverImageUrl,
			&i.CoverAltText,
			&i.IsActive,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewsCount,
			&i.LikesCount,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsBlockByID = `-- name: GetNewsBlockByID :one
SELECT id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order FROM news_blocks WHERE id = $1
`

func (q *Queries) GetNewsBlockByID(ctx context.Context, id int32) (NewsBlock, error) {
	row := q.db.QueryRow(ctx, getNewsBlockByID, id)
	var i NewsBlock
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverImageUrl,
		&i.CoverAltText,
		&i.IsActive,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewsCount,
		&i.LikesCount,
		&i.SortOrder,
	)
	return i, err
}

const getNewsBlockWithItems = `-- name: GetNewsBlockWithItems :one
SELECT 
    nb.id,
    nb.title,
    nb.cover_image_url,
    nb.cover_alt_text,
    nb.is_active,
    nb.published_at,
    nb.created_at,
    nb.updated_at,
    nb.views_count,
    nb.likes_count,
    nb.sort_order,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', ni.id,
                'news_block_id', ni.news_block_id,
                'item_type', ni.item_type,
                'content', ni.content,
                'image_url', ni.image_url,
                'link_url', ni.link_url,
                'layout', ni.layout,
                'sort_order', ni.sort_order,
                'created_at', ni.created_at,
                'updated_at', ni.updated_at
            ) ORDER BY ni.sort_order ASC
        ) FROM news_items ni 
        WHERE ni.news_block_id = nb.id),
        '[]'::json
    ) as items
FROM news_blocks nb
WHERE nb.id = $1 AND nb.is_active = true
`

type GetNewsBlockWithItemsRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	CoverAltText  pgtype.Text        `json:"cover_alt_text"`
	IsActive      pgtype.Bool        `json:"is_active"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ViewsCount    pgtype.Int4        `json:"views_count"`
	LikesCount    pgtype.Int4        `json:"likes_count"`
	SortOrder     pgtype.Int4        `json:"sort_order"`
	Items         interface{}        `json:"items"`
}

func (q *Queries) GetNewsBlockWithItems(ctx context.Context, id int32) (GetNewsBlockWithItemsRow, error) {
	row := q.db.QueryRow(ctx, getNewsBlockWithItems, id)
	var i GetNewsBlockWithItemsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverImageUrl,
		&i.CoverAltText,
		&i.IsActive,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewsCount,
		&i.LikesCount,
		&i.SortOrder,
		&i.Items,
	)
	return i, err
}

const getNewsBlocks = `-- name: GetNewsBlocks :many


SELECT id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order FROM news_blocks 
ORDER BY sort_order ASC, id ASC
`

// news_blocks.sql
// ============================================
// NEWS BLOCKS - BASIC CRUD
// ============================================
func (q *Queries) GetNewsBlocks(ctx context.Context) ([]NewsBlock, error) {
	rows, err := q.db.Query(ctx, getNewsBlocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsBlock
	for rows.Next() {
		var i NewsBlock
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverImageUrl,
			&i.CoverAltText,
			&i.IsActive,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewsCount,
			&i.LikesCount,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsItemByID = `-- name: GetNewsItemByID :one
SELECT id, news_block_id, item_type, content, image_url, link_url, layout, sort_order, created_at, updated_at FROM news_items WHERE id = $1
`

func (q *Queries) GetNewsItemByID(ctx context.Context, id int32) (NewsItem, error) {
	row := q.db.QueryRow(ctx, getNewsItemByID, id)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.NewsBlockID,
		&i.ItemType,
		&i.Content,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Layout,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsItemsByBlock = `-- name: GetNewsItemsByBlock :many

SELECT id, news_block_id, item_type, content, image_url, link_url, layout, sort_order, created_at, updated_at FROM news_items 
WHERE news_block_id = $1 
ORDER BY sort_order ASC, id ASC
`

// ============================================
// NEWS ITEMS
// ============================================
func (q *Queries) GetNewsItemsByBlock(ctx context.Context, newsBlockID int32) ([]NewsItem, error) {
	rows, err := q.db.Query(ctx, getNewsItemsByBlock, newsBlockID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsItem
	for rows.Next() {
		var i NewsItem
		if err := rows.Scan(
			&i.ID,
			&i.NewsBlockID,
			&i.ItemType,
			&i.Content,
			&i.ImageUrl,
			&i.LinkUrl,
			&i.Layout,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsList = `-- name: GetNewsList :many
SELECT 
    nb.id,
    nb.title,
    nb.cover_image_url,
    nb.cover_alt_text,
    nb.is_active,
    nb.published_at,
    nb.created_at,
    nb.updated_at,
    nb.views_count,
    nb.likes_count,
    nb.sort_order,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', ni.id,
                'news_block_id', ni.news_block_id,
                'item_type', ni.item_type,
                'content', ni.content,
                'image_url', ni.image_url,
                'link_url', ni.link_url,
                'layout', ni.layout,
                'sort_order', ni.sort_order,
                'created_at', ni.created_at,
                'updated_at', ni.updated_at
            ) ORDER BY ni.sort_order ASC
        ) FROM news_items ni 
        WHERE ni.news_block_id = nb.id),
        '[]'::json
    ) as items
FROM news_blocks nb
WHERE nb.is_active = true
    AND (
        $1::text = '' 
        OR nb.title ILIKE '%' || $1 || '%' 
        OR EXISTS (
            SELECT 1 FROM news_items ni 
            WHERE ni.news_block_id = nb.id 
            AND ni.content ILIKE '%' || $1 || '%'
        )
    )
ORDER BY 
    CASE 
        WHEN $2::text = 'published_at' AND $3::text = 'asc' THEN nb.published_at 
    END ASC,
    CASE 
        WHEN $2::text = 'published_at' AND $3::text = 'desc' THEN nb.published_at 
    END DESC,
    CASE 
        WHEN $2::text = 'views_count' AND $3::text = 'asc' THEN nb.views_count 
    END ASC,
    CASE 
        WHEN $2::text = 'views_count' AND $3::text = 'desc' THEN nb.views_count 
    END DESC,
    CASE 
        WHEN $2::text = 'likes_count' AND $3::text = 'asc' THEN nb.likes_count 
    END ASC,
    CASE 
        WHEN $2::text = 'likes_count' AND $3::text = 'desc' THEN nb.likes_count 
    END DESC,
    nb.published_at DESC
LIMIT $5 OFFSET $4
`

type GetNewsListParams struct {
	Search    string `json:"search"`
	SortBy    string `json:"sort_by"`
	SortOrder string `json:"sort_order"`
	Offsetval int32  `json:"offsetval"`
	Limitval  int32  `json:"limitval"`
}

type GetNewsListRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	CoverAltText  pgtype.Text        `json:"cover_alt_text"`
	IsActive      pgtype.Bool        `json:"is_active"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ViewsCount    pgtype.Int4        `json:"views_count"`
	LikesCount    pgtype.Int4        `json:"likes_count"`
	SortOrder     pgtype.Int4        `json:"sort_order"`
	Items         interface{}        `json:"items"`
}

// ============================================
// NEWS BLOCKS - PUBLIC API (FILTERS, SEARCH, PAGINATION)
// ============================================
func (q *Queries) GetNewsList(ctx context.Context, arg GetNewsListParams) ([]GetNewsListRow, error) {
	rows, err := q.db.Query(ctx, getNewsList,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewsListRow
	for rows.Next() {
		var i GetNewsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverImageUrl,
			&i.CoverAltText,
			&i.IsActive,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewsCount,
			&i.LikesCount,
			&i.SortOrder,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewsListCount = `-- name: GetNewsListCount :one
SELECT COUNT(*)
FROM news_blocks nb
WHERE nb.is_active = true
    AND (
        $1::text = '' 
        OR nb.title ILIKE '%' || $1 || '%' 
        OR EXISTS (
            SELECT 1 FROM news_items ni 
            WHERE ni.news_block_id = nb.id 
            AND ni.content ILIKE '%' || $1 || '%'
        )
    )
`

func (q *Queries) GetNewsListCount(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, getNewsListCount, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRelatedNews = `-- name: GetRelatedNews :many
SELECT id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order
FROM news_blocks
WHERE is_active = true 
    AND id != $1
ORDER BY published_at DESC
LIMIT $2
`

type GetRelatedNewsParams struct {
	ID       int32 `json:"id"`
	Limitval int32 `json:"limitval"`
}

func (q *Queries) GetRelatedNews(ctx context.Context, arg GetRelatedNewsParams) ([]NewsBlock, error) {
	rows, err := q.db.Query(ctx, getRelatedNews, arg.ID, arg.Limitval)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsBlock
	for rows.Next() {
		var i NewsBlock
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverImageUrl,
			&i.CoverAltText,
			&i.IsActive,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ViewsCount,
			&i.LikesCount,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementNewsBlockViews = `-- name: IncrementNewsBlockViews :exec

UPDATE news_blocks 
SET views_count = views_count + 1 
WHERE id = $1
`

// ============================================
// NEWS BLOCKS - STATISTICS
// ============================================
func (q *Queries) IncrementNewsBlockViews(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, incrementNewsBlockViews, id)
	return err
}

const reorderNewsBlock = `-- name: ReorderNewsBlock :exec
UPDATE news_blocks 
SET sort_order = $2, updated_at = NOW()
WHERE id = $1
`

type ReorderNewsBlockParams struct {
	ID        int32       `json:"id"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) ReorderNewsBlock(ctx context.Context, arg ReorderNewsBlockParams) error {
	_, err := q.db.Exec(ctx, reorderNewsBlock, arg.ID, arg.SortOrder)
	return err
}

const reorderNewsItem = `-- name: ReorderNewsItem :exec
UPDATE news_items 
SET sort_order = $2, updated_at = NOW()
WHERE id = $1
`

type ReorderNewsItemParams struct {
	ID        int32       `json:"id"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) ReorderNewsItem(ctx context.Context, arg ReorderNewsItemParams) error {
	_, err := q.db.Exec(ctx, reorderNewsItem, arg.ID, arg.SortOrder)
	return err
}

const toggleNewsBlockLike = `-- name: ToggleNewsBlockLike :exec
UPDATE news_blocks 
SET likes_count = likes_count + 1 
WHERE id = $1
`

func (q *Queries) ToggleNewsBlockLike(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, toggleNewsBlockLike, id)
	return err
}

const updateNewsBlock = `-- name: UpdateNewsBlock :one
UPDATE news_blocks 
SET 
    title = COALESCE($2, title),
    cover_image_url = COALESCE($3, cover_image_url),
    cover_alt_text = COALESCE($4, cover_alt_text),
    is_active = COALESCE($5, is_active),
    published_at = COALESCE($6, published_at),
    sort_order = COALESCE($7, sort_order),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, cover_image_url, cover_alt_text, is_active, published_at, created_at, updated_at, views_count, likes_count, sort_order
`

type UpdateNewsBlockParams struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	CoverAltText  pgtype.Text        `json:"cover_alt_text"`
	IsActive      pgtype.Bool        `json:"is_active"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	SortOrder     pgtype.Int4        `json:"sort_order"`
}

func (q *Queries) UpdateNewsBlock(ctx context.Context, arg UpdateNewsBlockParams) (NewsBlock, error) {
	row := q.db.QueryRow(ctx, updateNewsBlock,
		arg.ID,
		arg.Title,
		arg.CoverImageUrl,
		arg.CoverAltText,
		arg.IsActive,
		arg.PublishedAt,
		arg.SortOrder,
	)
	var i NewsBlock
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CoverImageUrl,
		&i.CoverAltText,
		&i.IsActive,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ViewsCount,
		&i.LikesCount,
		&i.SortOrder,
	)
	return i, err
}

const updateNewsItem = `-- name: UpdateNewsItem :one
UPDATE news_items 
SET 
    item_type = COALESCE($2, item_type),
    content = COALESCE($3, content),
    image_url = COALESCE($4, image_url),
    link_url = COALESCE($5, link_url),
    layout = COALESCE($6, layout),
    sort_order = COALESCE($7, sort_order),
    updated_at = NOW()
WHERE id = $1
RETURNING id, news_block_id, item_type, content, image_url, link_url, layout, sort_order, created_at, updated_at
`

type UpdateNewsItemParams struct {
	ID        int32            `json:"id"`
	ItemType  NewsItemTypeEnum `json:"item_type"`
	Content   pgtype.Text      `json:"content"`
	ImageUrl  pgtype.Text      `json:"image_url"`
	LinkUrl   pgtype.Text      `json:"link_url"`
	Layout    pgtype.Text      `json:"layout"`
	SortOrder pgtype.Int4      `json:"sort_order"`
}

func (q *Queries) UpdateNewsItem(ctx context.Context, arg UpdateNewsItemParams) (NewsItem, error) {
	row := q.db.QueryRow(ctx, updateNewsItem,
		arg.ID,
		arg.ItemType,
		arg.Content,
		arg.ImageUrl,
		arg.LinkUrl,
		arg.Layout,
		arg.SortOrder,
	)
	var i NewsItem
	err := row.Scan(
		&i.ID,
		&i.NewsBlockID,
		&i.ItemType,
		&i.Content,
		&i.ImageUrl,
		&i.LinkUrl,
		&i.Layout,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
