// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: order.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFromPreorderItems = `-- name: DeleteFromPreorderItems :exec
DELETE FROM preorderItems
WHERE orderid = $1
`

func (q *Queries) DeleteFromPreorderItems(ctx context.Context, orderid int32) error {
	_, err := q.db.Exec(ctx, deleteFromPreorderItems, orderid)
	return err
}

const getFullPreorderCount = `-- name: GetFullPreorderCount :one
SELECT coalesce(SUM(quantity), 0)
FROM preorderItems
WHERE orderid = $1
`

func (q *Queries) GetFullPreorderCount(ctx context.Context, orderid int32) (interface{}, error) {
	row := q.db.QueryRow(ctx, getFullPreorderCount, orderid)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getOrder = `-- name: GetOrder :one
SELECT id,
    status,
    customerId,
    hash,
    unregistercustomerid
FROM orders
WHERE id = $1
`

type GetOrderRow struct {
	ID                   int32       `json:"id"`
	Status               StatusEnum  `json:"status"`
	Customerid           pgtype.Int4 `json:"customerid"`
	Hash                 string      `json:"hash"`
	Unregistercustomerid pgtype.Int4 `json:"unregistercustomerid"`
}

func (q *Queries) GetOrder(ctx context.Context, id int32) (GetOrderRow, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i GetOrderRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Customerid,
		&i.Hash,
		&i.Unregistercustomerid,
	)
	return i, err
}

const getOrderDataById = `-- name: GetOrderDataById :many
SELECT id,
    productid AS prid,
    size,
    quantity
FROM orderItems
WHERE orderid = $1
`

type GetOrderDataByIdRow struct {
	ID       int32       `json:"id"`
	Prid     pgtype.Int4 `json:"prid"`
	Size     pgtype.Text `json:"size"`
	Quantity pgtype.Int4 `json:"quantity"`
}

func (q *Queries) GetOrderDataById(ctx context.Context, orderid pgtype.Int4) ([]GetOrderDataByIdRow, error) {
	rows, err := q.db.Query(ctx, getOrderDataById, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderDataByIdRow
	for rows.Next() {
		var i GetOrderDataByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Prid,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderIdByHashUrl = `-- name: GetOrderIdByHashUrl :one
SELECT id
FROM orders
WHERE hash = $1
`

func (q *Queries) GetOrderIdByHashUrl(ctx context.Context, hash string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrderIdByHashUrl, hash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getPreorderDataById = `-- name: GetPreorderDataById :many
SELECT id,
    productid AS prid,
    size,
    quantity
FROM preorderItems
WHERE orderid = $1
`

type GetPreorderDataByIdRow struct {
	ID       int32       `json:"id"`
	Prid     int32       `json:"prid"`
	Size     pgtype.Text `json:"size"`
	Quantity int32       `json:"quantity"`
}

func (q *Queries) GetPreorderDataById(ctx context.Context, orderid int32) ([]GetPreorderDataByIdRow, error) {
	rows, err := q.db.Query(ctx, getPreorderDataById, orderid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPreorderDataByIdRow
	for rows.Next() {
		var i GetPreorderDataByIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Prid,
			&i.Size,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreorderIdByHashUrl = `-- name: GetPreorderIdByHashUrl :one
SELECT id
FROM preorder
WHERE hashUrl = $1
`

func (q *Queries) GetPreorderIdByHashUrl(ctx context.Context, hashurl string) (int32, error) {
	row := q.db.QueryRow(ctx, getPreorderIdByHashUrl, hashurl)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getQuantityFromPreorderItems = `-- name: GetQuantityFromPreorderItems :one
SELECT quantity
FROM preorderitems
WHERE orderid = $1
    AND size = $2
    AND productid = $3
`

type GetQuantityFromPreorderItemsParams struct {
	Orderid   int32       `json:"orderid"`
	Size      pgtype.Text `json:"size"`
	Productid int32       `json:"productid"`
}

func (q *Queries) GetQuantityFromPreorderItems(ctx context.Context, arg GetQuantityFromPreorderItemsParams) (int32, error) {
	row := q.db.QueryRow(ctx, getQuantityFromPreorderItems, arg.Orderid, arg.Size, arg.Productid)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (
        orderdate,
        status,
        deliveryPrice,
        deliveryType,
        unregistercustomerid,
        hash
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertOrderParams struct {
	Orderdate            pgtype.Date  `json:"orderdate"`
	Status               StatusEnum   `json:"status"`
	Deliveryprice        int32        `json:"deliveryprice"`
	Deliverytype         DeliveryEnum `json:"deliverytype"`
	Unregistercustomerid pgtype.Int4  `json:"unregistercustomerid"`
	Hash                 string       `json:"hash"`
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.Orderdate,
		arg.Status,
		arg.Deliveryprice,
		arg.Deliverytype,
		arg.Unregistercustomerid,
		arg.Hash,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertPreorder = `-- name: InsertPreorder :one
INSERT INTO preorderItems (orderid, productid, size, quantity)
VALUES ($1, $2, $3, 1)
RETURNING id
`

type InsertPreorderParams struct {
	Orderid   int32       `json:"orderid"`
	Productid int32       `json:"productid"`
	Size      pgtype.Text `json:"size"`
}

func (q *Queries) InsertPreorder(ctx context.Context, arg InsertPreorderParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertPreorder, arg.Orderid, arg.Productid, arg.Size)
	var id int32
	err := row.Scan(&id)
	return id, err
}
