// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: promocodes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPromoCodeUsageByCustomer = `-- name: CheckPromoCodeUsageByCustomer :one
SELECT COUNT(*) as used_count
FROM promo_code_usage
WHERE promo_code_id = $1 
  AND customer_id = $2
`

type CheckPromoCodeUsageByCustomerParams struct {
	PromoCodeID int32       `json:"promo_code_id"`
	CustomerID  pgtype.Int4 `json:"customer_id"`
}

func (q *Queries) CheckPromoCodeUsageByCustomer(ctx context.Context, arg CheckPromoCodeUsageByCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkPromoCodeUsageByCustomer, arg.PromoCodeID, arg.CustomerID)
	var used_count int64
	err := row.Scan(&used_count)
	return used_count, err
}

const countPromoCodesWithFilters = `-- name: CountPromoCodesWithFilters :one
SELECT COUNT(*) as total
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE 
    ($1 IS NULL OR pc.code ILIKE '%' || $1 || '%')
    AND ($2 IS NULL OR pc.is_active = $2)
    AND ($3 IS NULL OR pc.applies_to = $3)
    AND (pc.starts_at >= $4 OR $4 IS NULL)
    AND (pc.starts_at <= $5 OR $5 IS NULL)
`

type CountPromoCodesWithFiltersParams struct {
	Code       interface{}        `json:"code"`
	IsActive   interface{}        `json:"is_active"`
	AppliesTo  interface{}        `json:"applies_to"`
	StartsFrom pgtype.Timestamptz `json:"starts_from"`
	StartsTo   pgtype.Timestamptz `json:"starts_to"`
}

func (q *Queries) CountPromoCodesWithFilters(ctx context.Context, arg CountPromoCodesWithFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPromoCodesWithFilters,
		arg.Code,
		arg.IsActive,
		arg.AppliesTo,
		arg.StartsFrom,
		arg.StartsTo,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createPromoCode = `-- name: CreatePromoCode :one
INSERT INTO promo_codes (
    code,
    name,
    description,
    discount_type,
    discount_value,
    applies_to,
    collection_id,
    min_order,
    max_order,
    max_discount,
    starts_at,
    ends_at,
    usage_limit,
    per_user_limit,
    is_active
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
) RETURNING id, code, name, description, discount_type, discount_value, applies_to, collection_id, min_order, max_order, max_discount, starts_at, ends_at, usage_limit, per_user_limit, is_active, created_at, updated_at
`

type CreatePromoCodeParams struct {
	Code          string             `json:"code"`
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  string             `json:"discount_type"`
	DiscountValue int32              `json:"discount_value"`
	AppliesTo     string             `json:"applies_to"`
	CollectionID  pgtype.Int4        `json:"collection_id"`
	MinOrder      pgtype.Int4        `json:"min_order"`
	MaxOrder      pgtype.Int4        `json:"max_order"`
	MaxDiscount   pgtype.Int4        `json:"max_discount"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	UsageLimit    pgtype.Int4        `json:"usage_limit"`
	PerUserLimit  pgtype.Int4        `json:"per_user_limit"`
	IsActive      pgtype.Bool        `json:"is_active"`
}

func (q *Queries) CreatePromoCode(ctx context.Context, arg CreatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, createPromoCode,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
		arg.AppliesTo,
		arg.CollectionID,
		arg.MinOrder,
		arg.MaxOrder,
		arg.MaxDiscount,
		arg.StartsAt,
		arg.EndsAt,
		arg.UsageLimit,
		arg.PerUserLimit,
		arg.IsActive,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.AppliesTo,
		&i.CollectionID,
		&i.MinOrder,
		&i.MaxOrder,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.UsageLimit,
		&i.PerUserLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPromoCodeUsage = `-- name: CreatePromoCodeUsage :one
INSERT INTO promo_code_usage (
    promo_code_id,
    order_id,
    customer_id,
    discount_amount,
    promo_code_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, promo_code_id, order_id, customer_id, promo_code_snapshot, discount_amount, used_at
`

type CreatePromoCodeUsageParams struct {
	PromoCodeID       int32       `json:"promo_code_id"`
	OrderID           int32       `json:"order_id"`
	CustomerID        pgtype.Int4 `json:"customer_id"`
	DiscountAmount    int32       `json:"discount_amount"`
	PromoCodeSnapshot []byte      `json:"promo_code_snapshot"`
}

func (q *Queries) CreatePromoCodeUsage(ctx context.Context, arg CreatePromoCodeUsageParams) (PromoCodeUsage, error) {
	row := q.db.QueryRow(ctx, createPromoCodeUsage,
		arg.PromoCodeID,
		arg.OrderID,
		arg.CustomerID,
		arg.DiscountAmount,
		arg.PromoCodeSnapshot,
	)
	var i PromoCodeUsage
	err := row.Scan(
		&i.ID,
		&i.PromoCodeID,
		&i.OrderID,
		&i.CustomerID,
		&i.PromoCodeSnapshot,
		&i.DiscountAmount,
		&i.UsedAt,
	)
	return i, err
}

const deactivateExpiredPromoCodes = `-- name: DeactivateExpiredPromoCodes :exec
UPDATE promo_codes
SET is_active = false,
    updated_at = NOW()
WHERE is_active = true
  AND ends_at IS NOT NULL
  AND ends_at < NOW()
`

func (q *Queries) DeactivateExpiredPromoCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateExpiredPromoCodes)
	return err
}

const deletePromoCode = `-- name: DeletePromoCode :exec
DELETE FROM promo_codes WHERE id = $1
`

func (q *Queries) DeletePromoCode(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePromoCode, id)
	return err
}

const getActivePromoCodes = `-- name: GetActivePromoCodes :many
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    ) as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE pc.is_active = true
  AND NOW() BETWEEN pc.starts_at AND COALESCE(pc.ends_at, 'infinity')
  AND (pc.usage_limit = 0 OR (
      SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id
  ) < pc.usage_limit)
ORDER BY pc.id DESC
`

type GetActivePromoCodesRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     interface{}        `json:"usage_count"`
}

func (q *Queries) GetActivePromoCodes(ctx context.Context) ([]GetActivePromoCodesRow, error) {
	rows, err := q.db.Query(ctx, getActivePromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActivePromoCodesRow
	for rows.Next() {
		var i GetActivePromoCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.AppliesTo,
			&i.CollectionID,
			&i.MinOrder,
			&i.MaxOrder,
			&i.MaxDiscount,
			&i.StartsAt,
			&i.EndsAt,
			&i.UsageLimit,
			&i.PerUserLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionSlug,
			&i.CollectionName,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPromoCodeByCode = `-- name: GetPromoCodeByCode :one
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    ) as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE pc.code = $1
`

type GetPromoCodeByCodeRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     interface{}        `json:"usage_count"`
}

func (q *Queries) GetPromoCodeByCode(ctx context.Context, code string) (GetPromoCodeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByCode, code)
	var i GetPromoCodeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.AppliesTo,
		&i.CollectionID,
		&i.MinOrder,
		&i.MaxOrder,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.UsageLimit,
		&i.PerUserLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionSlug,
		&i.CollectionName,
		&i.UsageCount,
	)
	return i, err
}

const getPromoCodeByID = `-- name: GetPromoCodeByID :one
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    )::bigint as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE pc.id = $1
`

type GetPromoCodeByIDRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     int64              `json:"usage_count"`
}

func (q *Queries) GetPromoCodeByID(ctx context.Context, id int32) (GetPromoCodeByIDRow, error) {
	row := q.db.QueryRow(ctx, getPromoCodeByID, id)
	var i GetPromoCodeByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.AppliesTo,
		&i.CollectionID,
		&i.MinOrder,
		&i.MaxOrder,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.UsageLimit,
		&i.PerUserLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionSlug,
		&i.CollectionName,
		&i.UsageCount,
	)
	return i, err
}

const getPromoCodeUsageByOrder = `-- name: GetPromoCodeUsageByOrder :one
SELECT 
    pu.id, pu.promo_code_id, pu.order_id, pu.customer_id, pu.promo_code_snapshot, pu.discount_amount, pu.used_at,
    pc.code,
    pc.name,
    pc.discount_type,
    pc.discount_value,
    pu.promo_code_snapshot
FROM promo_code_usage pu
JOIN promo_codes pc ON pu.promo_code_id = pc.id
WHERE pu.order_id = $1
LIMIT 1
`

type GetPromoCodeUsageByOrderRow struct {
	ID                  int32              `json:"id"`
	PromoCodeID         int32              `json:"promo_code_id"`
	OrderID             int32              `json:"order_id"`
	CustomerID          pgtype.Int4        `json:"customer_id"`
	PromoCodeSnapshot   []byte             `json:"promo_code_snapshot"`
	DiscountAmount      int32              `json:"discount_amount"`
	UsedAt              pgtype.Timestamptz `json:"used_at"`
	Code                string             `json:"code"`
	Name                pgtype.Text        `json:"name"`
	DiscountType        string             `json:"discount_type"`
	DiscountValue       int32              `json:"discount_value"`
	PromoCodeSnapshot_2 []byte             `json:"promo_code_snapshot_2"`
}

func (q *Queries) GetPromoCodeUsageByOrder(ctx context.Context, orderID int32) (GetPromoCodeUsageByOrderRow, error) {
	row := q.db.QueryRow(ctx, getPromoCodeUsageByOrder, orderID)
	var i GetPromoCodeUsageByOrderRow
	err := row.Scan(
		&i.ID,
		&i.PromoCodeID,
		&i.OrderID,
		&i.CustomerID,
		&i.PromoCodeSnapshot,
		&i.DiscountAmount,
		&i.UsedAt,
		&i.Code,
		&i.Name,
		&i.DiscountType,
		&i.DiscountValue,
		&i.PromoCodeSnapshot_2,
	)
	return i, err
}

const getPromoCodeUsageStats = `-- name: GetPromoCodeUsageStats :one
SELECT 
    COUNT(*) as total_uses,
    COALESCE(SUM(discount_amount), 0) as total_discount,
    COUNT(DISTINCT customer_id) as unique_customers
FROM promo_code_usage
WHERE promo_code_id = $1
`

type GetPromoCodeUsageStatsRow struct {
	TotalUses       int64       `json:"total_uses"`
	TotalDiscount   interface{} `json:"total_discount"`
	UniqueCustomers int64       `json:"unique_customers"`
}

func (q *Queries) GetPromoCodeUsageStats(ctx context.Context, id int32) (GetPromoCodeUsageStatsRow, error) {
	row := q.db.QueryRow(ctx, getPromoCodeUsageStats, id)
	var i GetPromoCodeUsageStatsRow
	err := row.Scan(&i.TotalUses, &i.TotalDiscount, &i.UniqueCustomers)
	return i, err
}

const listPromoCodes = `-- name: ListPromoCodes :many
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    ) as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
ORDER BY pc.id DESC
`

type ListPromoCodesRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     interface{}        `json:"usage_count"`
}

func (q *Queries) ListPromoCodes(ctx context.Context) ([]ListPromoCodesRow, error) {
	rows, err := q.db.Query(ctx, listPromoCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromoCodesRow
	for rows.Next() {
		var i ListPromoCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.AppliesTo,
			&i.CollectionID,
			&i.MinOrder,
			&i.MaxOrder,
			&i.MaxDiscount,
			&i.StartsAt,
			&i.EndsAt,
			&i.UsageLimit,
			&i.PerUserLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionSlug,
			&i.CollectionName,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromoCodesWithFilters = `-- name: ListPromoCodesWithFilters :many
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    ) as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE 
    ($1 IS NULL OR pc.code ILIKE '%' || $1 || '%')
    AND ($2 IS NULL OR pc.is_active = $2)
    AND ($3 IS NULL OR pc.applies_to = $3)
    AND (pc.starts_at >= $4 OR $4 IS NULL)
    AND (pc.starts_at <= $5 OR $5 IS NULL)
ORDER BY 
    CASE WHEN $6 = 'created_at' THEN pc.created_at END DESC,
    CASE WHEN $6 = 'code' THEN pc.code END,
    CASE WHEN $6 = 'discount_value' THEN pc.discount_value END,
    pc.id DESC
LIMIT $8
OFFSET $7
`

type ListPromoCodesWithFiltersParams struct {
	Code       interface{}        `json:"code"`
	IsActive   interface{}        `json:"is_active"`
	AppliesTo  interface{}        `json:"applies_to"`
	StartsFrom pgtype.Timestamptz `json:"starts_from"`
	StartsTo   pgtype.Timestamptz `json:"starts_to"`
	SortBy     interface{}        `json:"sort_by"`
	Offsetval  int32              `json:"offsetval"`
	Limitval   int32              `json:"limitval"`
}

type ListPromoCodesWithFiltersRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     interface{}        `json:"usage_count"`
}

func (q *Queries) ListPromoCodesWithFilters(ctx context.Context, arg ListPromoCodesWithFiltersParams) ([]ListPromoCodesWithFiltersRow, error) {
	rows, err := q.db.Query(ctx, listPromoCodesWithFilters,
		arg.Code,
		arg.IsActive,
		arg.AppliesTo,
		arg.StartsFrom,
		arg.StartsTo,
		arg.SortBy,
		arg.Offsetval,
		arg.Limitval,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromoCodesWithFiltersRow
	for rows.Next() {
		var i ListPromoCodesWithFiltersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DiscountType,
			&i.DiscountValue,
			&i.AppliesTo,
			&i.CollectionID,
			&i.MinOrder,
			&i.MaxOrder,
			&i.MaxDiscount,
			&i.StartsAt,
			&i.EndsAt,
			&i.UsageLimit,
			&i.PerUserLimit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionSlug,
			&i.CollectionName,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromoCode = `-- name: UpdatePromoCode :one
UPDATE promo_codes
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    discount_type = COALESCE($3, discount_type),
    discount_value = COALESCE($4, discount_value),
    applies_to = COALESCE($5, applies_to),
    collection_id = COALESCE($6, collection_id),
    min_order = COALESCE($7, min_order),
    max_order = COALESCE($8, max_order),
    max_discount = COALESCE($9, max_discount),
    starts_at = COALESCE($10, starts_at),
    ends_at = $11,
    usage_limit = COALESCE($12, usage_limit),
    per_user_limit = COALESCE($13, per_user_limit),
    is_active = COALESCE($14, is_active),
    updated_at = NOW()
WHERE id = $15
RETURNING id, code, name, description, discount_type, discount_value, applies_to, collection_id, min_order, max_order, max_discount, starts_at, ends_at, usage_limit, per_user_limit, is_active, created_at, updated_at
`

type UpdatePromoCodeParams struct {
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	DiscountType  pgtype.Text        `json:"discount_type"`
	DiscountValue pgtype.Int4        `json:"discount_value"`
	AppliesTo     pgtype.Text        `json:"applies_to"`
	CollectionID  pgtype.Int4        `json:"collection_id"`
	MinOrder      pgtype.Int4        `json:"min_order"`
	MaxOrder      pgtype.Int4        `json:"max_order"`
	MaxDiscount   pgtype.Int4        `json:"max_discount"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	UsageLimit    pgtype.Int4        `json:"usage_limit"`
	PerUserLimit  pgtype.Int4        `json:"per_user_limit"`
	IsActive      pgtype.Bool        `json:"is_active"`
	ID            int32              `json:"id"`
}

func (q *Queries) UpdatePromoCode(ctx context.Context, arg UpdatePromoCodeParams) (PromoCode, error) {
	row := q.db.QueryRow(ctx, updatePromoCode,
		arg.Name,
		arg.Description,
		arg.DiscountType,
		arg.DiscountValue,
		arg.AppliesTo,
		arg.CollectionID,
		arg.MinOrder,
		arg.MaxOrder,
		arg.MaxDiscount,
		arg.StartsAt,
		arg.EndsAt,
		arg.UsageLimit,
		arg.PerUserLimit,
		arg.IsActive,
		arg.ID,
	)
	var i PromoCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.AppliesTo,
		&i.CollectionID,
		&i.MinOrder,
		&i.MaxOrder,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.UsageLimit,
		&i.PerUserLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validatePromoCode = `-- name: ValidatePromoCode :one
SELECT 
    pc.id, pc.code, pc.name, pc.description, pc.discount_type, pc.discount_value, pc.applies_to, pc.collection_id, pc.min_order, pc.max_order, pc.max_discount, pc.starts_at, pc.ends_at, pc.usage_limit, pc.per_user_limit, pc.is_active, pc.created_at, pc.updated_at,
    c.slug as collection_slug,
    c.name as collection_name,
    COALESCE(
        (SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id),
        0
    ) as usage_count
FROM promo_codes pc
LEFT JOIN collections c ON pc.collection_id = c.id
WHERE pc.code = $1
  AND pc.is_active = true
  AND NOW() BETWEEN pc.starts_at AND COALESCE(pc.ends_at, 'infinity')
  AND (pc.usage_limit = 0 OR (
      SELECT COUNT(*) FROM promo_code_usage WHERE promo_code_id = pc.id
  ) < pc.usage_limit)
LIMIT 1
`

type ValidatePromoCodeRow struct {
	ID             int32              `json:"id"`
	Code           string             `json:"code"`
	Name           pgtype.Text        `json:"name"`
	Description    pgtype.Text        `json:"description"`
	DiscountType   string             `json:"discount_type"`
	DiscountValue  int32              `json:"discount_value"`
	AppliesTo      string             `json:"applies_to"`
	CollectionID   pgtype.Int4        `json:"collection_id"`
	MinOrder       pgtype.Int4        `json:"min_order"`
	MaxOrder       pgtype.Int4        `json:"max_order"`
	MaxDiscount    pgtype.Int4        `json:"max_discount"`
	StartsAt       pgtype.Timestamptz `json:"starts_at"`
	EndsAt         pgtype.Timestamptz `json:"ends_at"`
	UsageLimit     pgtype.Int4        `json:"usage_limit"`
	PerUserLimit   pgtype.Int4        `json:"per_user_limit"`
	IsActive       pgtype.Bool        `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CollectionSlug pgtype.Text        `json:"collection_slug"`
	CollectionName pgtype.Text        `json:"collection_name"`
	UsageCount     interface{}        `json:"usage_count"`
}

func (q *Queries) ValidatePromoCode(ctx context.Context, code string) (ValidatePromoCodeRow, error) {
	row := q.db.QueryRow(ctx, validatePromoCode, code)
	var i ValidatePromoCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DiscountType,
		&i.DiscountValue,
		&i.AppliesTo,
		&i.CollectionID,
		&i.MinOrder,
		&i.MaxOrder,
		&i.MaxDiscount,
		&i.StartsAt,
		&i.EndsAt,
		&i.UsageLimit,
		&i.PerUserLimit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionSlug,
		&i.CollectionName,
		&i.UsageCount,
	)
	return i, err
}
