// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckCustomerExistence(ctx context.Context, arg CheckCustomerExistenceParams) (bool, error)
	CheckMail(ctx context.Context, mail string) (bool, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (int32, error)
	DeleteFromPreorderItems(ctx context.Context, orderid int32) error
	DeleteFromVerifivation(ctx context.Context, id int32) error
	DeleteVerification(ctx context.Context, id int32) error
	GetBaseCustomerData(ctx context.Context, mail string) (GetBaseCustomerDataRow, error)
	GetCointIdByName(ctx context.Context, dollar_1 string) ([]GetCointIdByNameRow, error)
	GetCollections(ctx context.Context, arg GetCollectionsParams) ([]GetCollectionsRow, error)
	GetCustomerData(ctx context.Context, id int32) (GetCustomerDataRow, error)
	GetCustomerId(ctx context.Context, mail string) (int32, error)
	GetFiltersByString(ctx context.Context, dollar_1 string) ([]GetFiltersByStringRow, error)
	GetFirms(ctx context.Context) ([]GetFirmsRow, error)
	GetFullPreorderCount(ctx context.Context, orderid int32) (interface{}, error)
	GetOrder(ctx context.Context, id int32) (GetOrderRow, error)
	GetOrderDataById(ctx context.Context, orderid pgtype.Int4) ([]GetOrderDataByIdRow, error)
	GetOrderIdByHashUrl(ctx context.Context, hash string) (int32, error)
	GetPassword(ctx context.Context, id int32) ([]byte, error)
	GetPreorderDataById(ctx context.Context, orderid int32) ([]GetPreorderDataByIdRow, error)
	GetPreorderIdByHashUrl(ctx context.Context, hashurl string) (int32, error)
	GetQuantityFromPreorderItems(ctx context.Context, arg GetQuantityFromPreorderItemsParams) (int32, error)
	GetSnickersByFirmName(ctx context.Context, firm string) ([]GetSnickersByFirmNameRow, error)
	GetSnickersByIds(ctx context.Context, id int32) ([]GetSnickersByIdsRow, error)
	GetSnickersByLineName(ctx context.Context, line string) ([]GetSnickersByLineNameRow, error)
	GetSnickersByName(ctx context.Context, arg GetSnickersByNameParams) ([]GetSnickersByNameRow, error)
	GetSnickersInfoById(ctx context.Context, id int32) (GetSnickersInfoByIdRow, error)
	GetSoloCollection(ctx context.Context, arg GetSoloCollectionParams) ([]GetSoloCollectionRow, error)
	GetUnregisterCustomer(ctx context.Context, id int32) (GetUnregisterCustomerRow, error)
	GetVerification(ctx context.Context, token string) (GetVerificationRow, error)
	InsertOrder(ctx context.Context, arg InsertOrderParams) (int32, error)
	InsertPreorder(ctx context.Context, arg InsertPreorderParams) (int32, error)
	InsertVerification(ctx context.Context, arg InsertVerificationParams) error
	SelectHistoryFromUniqueCustomer(ctx context.Context, id int32) ([]int32, error)
	SetUnregisterCustomer(ctx context.Context, arg SetUnregisterCustomerParams) (int32, error)
	UpdateCustomerPass(ctx context.Context, arg UpdateCustomerPassParams) error
	UpdateUniqueCustomerHistry(ctx context.Context, arg UpdateUniqueCustomerHistryParams) error
}

var _ Querier = (*Queries)(nil)
